In [1]:
import pandas as pd
dir = 'Dataset/Events2Text'

In [14]:
df_dataset = pd.read_json(f'{dir}/player2vec_dataset.json')
df_dataset.head()

,season,playerId,playerName,teamId,teamName,text,match
0,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Tackle da centrocampo, fascia destra (tackle...",2019-08-12_Man Utd_Chelsea
1,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Passaggio da centrocampo, fascia destra a cen...",2019-08-20_Wolves_Man Utd
2,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Passaggio da trequarti difensiva, centro dest...",2019-08-26_Man Utd_Crystal Palace
3,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Passaggio da trequarti difensiva, centro dest...",2019-09-01_Southampton_Man Utd
4,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Passaggio da centrocampo, centrale a centroca...",2019-09-15_Man Utd_Leicester

In [15]:
player_season_counts = df_dataset.groupby(['playerId', 'playerName', 'season']).size().reset_index(name='row_count')
print(len(player_season_counts))
player_season_counts.head()

22307

   playerId         playerName     season  row_count
0       217    Claudio Pizarro  2019-2020         18
1      2794  Souleymane Camara  2019-2020         13
2      2837      Jermain Defoe  2019-2020          1
3      2943   Christian Maggio  2020-2021          8
4      2987         Pepe Reina  2019-2020         14

In [39]:
#player_season_counts[[player_season_counts.playerId == 349207.0] and [player_season_counts.season == '2021-2022']]['row_count']
p = player_season_counts[(player_season_counts['playerId'] == 349207.0) & (player_season_counts['season'] == '2021-2022')]['row_count']
int(p.loc[p.index[0]])

38

In [16]:
vocab = getTotalVocab()
df_dataset['text'][0]

'Tackle  da centrocampo, fascia destra  (tackle perso). Spazzata  da difesa, centrale a trequarti difensiva, fascia sinistra  (spazzata efficace, spazzata effettuata di testa, colpo di testa). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da difesa, centro destra a difesa, centro sinistra  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da centrocampo, centro sinistra a centrocampo, centro sinistra  (preciso in avanti, preciso, corto preciso, di testa, in avanti, verso destra, passaggio di testa). Passaggio  da difesa, centro destra a difesa, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, fascia sinistra  (retropassaggio impreciso, impreciso, pallonetto/passaggio alto, lancio lungo impreciso, in avanti, verso sinistra, lancio lungo). Passaggio  da trequarti difensiva, fascia destra a difesa, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Recupero possesso  da trequarti difensiva, centro sinistra, Passaggio  da trequarti difensiva, centro sinistra a trequarti difensiva, fascia sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro sinistra  (preciso, lancio lungo preciso, retropassaggio, verso sinistra, lancio lungo). Passaggio  da trequarti difensiva, centro sinistra a difesa, centrale  (preciso, lancio lungo preciso, retropassaggio, verso destra, lancio lungo). Passaggio  da difesa, centrale a difesa, centrale  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, lancio lungo preciso, in avanti, verso destra, lancio lungo). Recupero possesso  da trequarti difensiva, fascia destra, Passaggio  da trequarti difensiva, fascia destra a centrocampo, fascia destra  (retropassaggio impreciso, impreciso, corto impreciso, in avanti, verso sinistra). Passaggio  da centrocampo, centrale a centrocampo, fascia destra  (preciso, corto preciso, in avanti, verso destra). Recupero possesso  da trequarti difensiva, centro destra, Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da difesa, centro destra a difesa, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso destra). Dribbling  da trequarti difensiva, centro sinistra  (dribbling riuscito), Passaggio  da trequarti difensiva, centro sinistra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da difesa, centro destra a difesa, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da difesa, fascia destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da centrocampo, fascia destra a centrocampo, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da difesa, centro destra a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio bloccato  da centrocampo, centro destra  (passaggio bloccato da un giocatore di movimento). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centrale  (preciso, corto preciso, in avanti, verso sinistra). Recupero possesso  da trequarti difensiva, centro sinistra, Passaggio  da trequarti difensiva, centro sinistra a trequarti difensiva, fascia destra  (preciso, corto preciso, retropassaggio, verso destra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, in avanti, verso sinistra). Recupero possesso  da difesa, centro destra, Passaggio  da difesa, centro destra a centrocampo, centro destra  (impreciso, lancio lungo impreciso, in avanti, verso destra, lancio lungo). Contesa pallone in aria  da difesa, centrale  (duello aereo perso, duello difensivo). Passaggio  da difesa, centro destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da difesa, centro destra a difesa, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da difesa, fascia destra a centrocampo, fascia destra  (retropassaggio impreciso, impreciso, lancio lungo impreciso, in avanti, verso sinistra, lancio lungo). Recupero possesso  da trequarti difensiva, fascia destra, Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso sinistra). Contesa pallone in aria  da centrocampo, centro sinistra  (duello aereo vinto, duello difensivo), Passaggio  da centrocampo, centro sinistra a centrocampo, fascia sinistra  (impreciso, corto impreciso, di testa, in avanti, verso sinistra, passaggio di testa). Passaggio  da trequarti offensiva, fascia sinistra a trequarti offensiva, fascia sinistra  (impreciso, lancio lungo impreciso, in avanti, verso sinistra, lancio lungo). Passaggio  da trequarti difensiva, centro sinistra a centrocampo, centro destra  (retropassaggio impreciso, impreciso, lancio lungo impreciso, in avanti, verso destra, lancio lungo). Spazzata  da difesa, centrale a trequarti difensiva, centro destra  (spazzata efficace, spazzata effettuata di testa, colpo di testa). Intercettazione  da trequarti difensiva, centrale  (intercettazione riuscita). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, preciso da punizione, in avanti, verso sinistra, calcio di punizione battuto). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da difesa, fascia destra a trequarti difensiva, centro destra  (retropassaggio impreciso, impreciso, lancio lungo impreciso, in avanti, verso sinistra, lancio lungo). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Sanzione   (ammonizione). Contesa pallone in aria  da difesa, centrale  (duello aereo perso, duello difensivo). Passaggio  da difesa, centro destra a trequarti difensiva, centro destra  (preciso, pallonetto/passaggio alto, lancio lungo preciso, in avanti, lancio lungo). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a centrocampo, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da trequarti difensiva, centro destra a centrocampo, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a centrocampo, fascia destra  (preciso in avanti, preciso, corto preciso, in avanti, verso destra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centrale  (preciso, corto preciso, in avanti, verso destra). Tocco palla  da trequarti difensiva, centro destra. Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, centro destra  (retropassaggio impreciso, impreciso, corto impreciso, verso sinistra). Passaggio  da centrocampo, fascia destra a centrocampo, fascia destra  (retropassaggio impreciso, impreciso, corto impreciso, in avanti, verso destra, azione offensiva). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso sinistra). Spazzata  da difesa, centro destra a trequarti difensiva, centro sinistra  (spazzata efficace). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a centrocampo, centro destra  (preciso in avanti, preciso, corto preciso, in avanti, verso sinistra). Passaggio  da centrocampo, centro destra a centrocampo, centro destra  (preciso in avanti, preciso, corto preciso, in avanti, verso sinistra). Salvataggio  da difesa, centro destra  (blocco effettuato da un giocatore di movimento, blocco effettuato da un giocatore di movimento). Passaggio  da centrocampo, centrale a centrocampo, centro destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da centrocampo, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, centro destra a centrocampo, centro destra  (preciso in avanti, preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, fascia destra  (preciso, corto preciso, retropassaggio, verso destra). Recupero possesso  da trequarti difensiva, centro sinistra, Passaggio  da trequarti difensiva, centro sinistra a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra)'

In [3]:
import os
s = 'Europa-Champions-League_2023-2024_teams'
for s in os.listdir('Dataset/Events2Text/TeamPlayerList'):
    print(s.split('_')[1])

2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024

In [ ]:
import utils
def getTeamsPlayerDict(path: str) -> set:
    team_list = {}
    #for file in os.listdir(path):
    for file in os.listdir(path):
        nazione = file.split('-')[0]
        season = file.split('_')[1]
        if season not in team_list.keys():
            team_list[season] = {}

        dict_file = utils.readJson(f'{path}/{file}')

        for k, v in dict_file.items():
            if nazione != 'Europa':
                team_list[season][k] = v


    return team_list

getTeamDict('Dataset/Events2Text/TeamPlayerList')['2021-2022']['80']

{'name': 'AC Milan',
 'players': {'141646.0': 'Mike Maignan',
  '343501.0': 'Sandro Tonali',
  '294163.0': 'Rade Krunic',
  '303115.0': 'Theo Hernández',
  '24444.0': 'Olivier Giroud',
  '317507.0': 'Fikayo Tomori',
  '20769.0': 'Simon Kjær',
  '365308.0': 'Alexis Saelemaekers',
  '349207.0': 'Rafael Leão',
  '260498.0': 'Davide Calabria',
  '317541.0': 'Brahim Díaz',
  '101735.0': 'Ante Rebic',
  '259102.0': 'Ismaël Bennacer',
  '101596.0': 'Alessandro Florenzi',
  '118158.0': 'Alessio Romagnoli',
  '388493.0': 'Daniel Maldini',
  '238773.0': 'Samu Castillejo',
  '277269.0': 'Franck Kessie',
  '3281.0': 'Zlatan Ibrahimovic',
  '135211.0': 'Tiémoué Bakayoko',
  '328968.0': 'Fodé Ballo-Touré',
  '391836.0': 'Pierre Kalulu',
  '337443.0': 'Matteo Gabbia',
  '332270.0': 'Pietro Pellegri',
  '401098.0': 'Junior Messias',
  '32676.0': 'Ciprian Tatarusanu',
  '294137.0': 'Andrea Conti',
  '411943.0': 'Luca Stanga'}}

In [ ]:
lista_1 = ["tiro fuori bersaglio dall'interno dell'area attacco, centro sinistra", "tiro fuori bersaglio dall'interno dell'area attacco, centro destra", "tiro dall'area di rigore attacco, centro sinistra", "parata fuori dall'area di rigore attacco, centro sinistra", "tiro dall'area di rigore attacco, centro destra", "parata fuori dall'area di rigore attacco, centro destra", 'perde il controllo del pallone correndo attacco, centro sinistra', "tiro dall'area piccola attacco, centro sinistra", 'parata su tiro fuori area attacco, centro sinistra', 'parata su tiro fuori area attacco, centro destra', 'perde il controllo del pallone correndo attacco, centro destra', 'tiro bloccato attacco, centro sinistra', "tiro dall'area piccola attacco, centro destra", "parata nell'area di rigore attacco, centro sinistra", 'perde il controllo del pallone attacco, centro sinistra', "tiro fuori bersaglio dall'interno dell'area attacco, centrale", 'rigore sbagliato attacco, centro destra', 'rigore sbagliato attacco, centro sinistra', 'perde il controllo del pallone attacco, centro destra', "blocco nell'area piccola attacco, centro sinistra"]
lista_2 = ["tiro fuori bersaglio dall'interno dell'area attacco, centro sinistra", "tiro fuori bersaglio dall'interno dell'area attacco, centro destra", "tiro dall'area di rigore attacco, centro sinistra", "parata fuori dall'area di rigore attacco, centro sinistra", "tiro dall'area di rigore attacco, centro destra", "parata fuori dall'area di rigore attacco, centro destra", "tiro dall'area piccola attacco, centro sinistra", 'azione eseguita con una parte del corpo diversa attacco, centro sinistra', 'parata su tiro fuori area attacco, centro sinistra', 'azione offensiva attacco, centro sinistra', 'azione di contropiede attacco, centro sinistra', 'parata su tiro fuori area attacco, centro destra', 'tiro bloccato attacco, centro sinistra', 'azione offensiva attacco, centro destra', 'azione eseguita con i piedi attacco, centro sinistra', "tiro dall'area piccola attacco, centro destra", "parata nell'area di rigore attacco, centro sinistra", 'azione bloccata attacco, centro sinistra', 'azione di contropiede attacco, centro destra', "tiro fuori bersaglio dall'interno dell'area attacco, centrale"]
k = 0
for i,j in zip(lista_1, lista_2):
    if i != j:
        k+=1
        print(f'{i} ---{j}')

k

perde il controllo del pallone correndo attacco, centro sinistra ---tiro dall'area piccola attacco, centro sinistra
tiro dall'area piccola attacco, centro sinistra ---azione eseguita con una parte del corpo diversa attacco, centro sinistra
parata su tiro fuori area attacco, centro destra ---azione offensiva attacco, centro sinistra
perde il controllo del pallone correndo attacco, centro destra ---azione di contropiede attacco, centro sinistra
tiro bloccato attacco, centro sinistra ---parata su tiro fuori area attacco, centro destra
tiro dall'area piccola attacco, centro destra ---tiro bloccato attacco, centro sinistra
parata nell'area di rigore attacco, centro sinistra ---azione offensiva attacco, centro destra
perde il controllo del pallone attacco, centro sinistra ---azione eseguita con i piedi attacco, centro sinistra
tiro fuori bersaglio dall'interno dell'area attacco, centrale ---tiro dall'area piccola attacco, centro destra
rigore sbagliato attacco, centro destra ---parata nell'area di rigore attacco, centro sinistra
rigore sbagliato attacco, centro sinistra ---azione bloccata attacco, centro sinistra
perde il controllo del pallone attacco, centro destra ---azione di contropiede attacco, centro destra
blocco nell'area piccola attacco, centro sinistra ---tiro fuori bersaglio dall'interno dell'area attacco, centrale

13

:

In [33]:
import utils
desc = utils.readJson('Descriptions/player_description_it.json')
i=0
print(len(desc.keys()))
for line in desc["480249.0"]['prompt'].split('\n'):
    if i > 0:
        print(line)
        #break
    i+=1
print(i)

Il file non è stato trovato.

AttributeError: 'NoneType' object has no attribute 'keys'

In [120]:
import utils
desc = utils.readJson('Descriptions/Descriptions/players_description_it_v4_post.json')

i = 0 
busq=0
no_desc =0
no_name = 0
agisci = False
for k, x in desc.items() :
    #if 'description' in x.keys() and i == 0:
        #print(x['name'], x['description'])
        #break
       
        #print(len(x['description'].split(' ')))
    if 'description' not in x.keys():
        no_desc +=1

    else:
        if 'Sergio Busquets' in x['description']:
            busq +=1
            if agisci:
                x.pop('description')
                continue
            print(k, x)
        elif 'Gerard Pique' in x['description']:
            busq +=1
            if agisci:
                x.pop('description')
                continue

            print(k, x)
        elif 'David De Gea' in x['description']:   
            busq +=1
            if agisci:
                x.pop('description')
                continue
            print(k, x)
        elif 'Zlatan Ibrahimovic' in x['description']:
            #x.pop('description')
            busq +=1
            if agisci:
                x.pop('description')
                continue
            print(k, x)

        if x['name'] not in x['description']:
            #if agisci:
                #x.pop('description')
            no_name+=1
            #print(k,x['name'], x)

    i+=1
if agisci:
    utils.writeJson(desc, 'Descriptions/Descriptions/players_description_it_v4_post.json')
busq, no_name

(0, 153)

In [140]:

desc = utils.readJson('Descriptions/Descriptions/players_description_it_v3.json')

*Portieri* 4-shot distillation prompting

In [165]:
p='13754.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['prompt'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Manuel Neuer

        Sei un osservatore calcistico professionista con esperienza nell'analisi delle caratteristiche tecniche e tattiche dei giocatori.
        Devi generare un rapporto dettagliato su un giocatore, basandoti sull'elenco delle azioni fornite che descrivono il suo stile di gioco durante le partite.
        Il tuo compito è analizzare questi dati e fornire un rapporto strutturato come segue:
        ###Input Data
            - Giocatore: Manuel Neuer
            - Azioni: ['tiro alto fuori bersaglio difesa, centrale', 'lancio lungo preciso difesa, centrale', 'preciso in avanti difesa, centrale', 'tiro alto vicino alla traversa difesa, centrale', 'tiro di destro difesa, centrale', 'tiro fuori bersaglio difesa, centrale', "tiro dall'area piccola difesa, centrale", 'corto preciso difesa, centrale', 'errore che porta a tiro difesa, centrale', 'tiro nello specchio difesa, centrale', 'tiro di poco fuori alto a sinistra difesa, centrale', 'tiro di poco fuori alto a destra difesa, centrale', 'tiro vicino al palo destro difesa, centrale', 'in avanti difesa, centrale', 'tiro bloccato difesa, centrale', 'assist di altro tipo difesa, centrale', 'da tiro fuori bersaglio difesa, centrale', 'lancio lungo difesa, centrale', 'salvataggio sulla linea difesa, centrale', 'tiro di sinistro difesa, centrale']

        Restituisci il report nel seguente formato:

        ###Formato output
            *Giocatore*:
            Manuel Neuer
            *Caratteristiche*:
            Evidenzia le caratteristiche tecnico tattiche che meglio rappresentano il giocatore
            *Punti di forza*:
            Evidenzia i punti di forza principali del giocatore emersi dal suo stile di gioco.
            *Debolezze*:
            Indica le aree in cui il giocatore deve migliorare.
            *Zone del campo predilette*:
            Identifica le zone del campo in cui il giocatore è più attivo o performa meglio.

        ###Note per l'analisi
            - Usa un linguaggio conciso e professionale.
            - Il report deve essere realistico e utile per scopi di osservazione calcistica.
            - Non generare codice o strutture di classe. Concentrati solo sull'analisi calcistica.
            - L'output deve essere in testo semplice, chiaramente formattato secondo la struttura sopra indicata.
            - Non scrivere il nome del giocatore.

        Genera solo il contenuto del rapporto. Non includere spiegazioni, istruzioni, o altre informazioni oltre a quelle richieste.
        ###Report generato:

In [138]:
p='141646.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Mike Maignan

        	Mike Maignan
		Caratteristiche:
			Giocatore molto abile nei lanci lunghi e precisi dalla propria area verso gli altri compagni d'equipe.
			Esempio: Lancio lungo preciso difesa, centrale
			Tecnique avanzate nella gestione della palla sotto pressione.
			Esempio: Tiro di destro difesa, centrale
			Possiede una buona visione di squadra ed è capace di trovare passaggi difficili tra i propri compagni.
			Esempio: Preciso in avanti difesa, centrale

		Punti di Forza:
			Specialità nelle situazioni di emergenza quando si trova davanti all'avversario.
			Esempio: Tiro di poco fuori alto a destra difesa, centrale
			Abitudine ad eseguire calci punitivi efficaci.
			Esempio: Da tiro fuori bersaglio difesa, centrale
			Buone capacita di controllo della palla anche in condizioni sfavorevoli.
			Esempio: Corto preciso difesa, centrale

		Difetti:
			Necessita di lavorare sulla precisione dei suoi tiraggi diretti contro il portiere avversario.
			Esempio: Errore che porta a tiro difesa, centrale
			Rischiosa tendenza a prendere decisioni affrettate sulle sue scelte di passaggio.
			Esempio: In avanti difesa, centrale
			Frequenti errori dovuti allo stress emotivo.
			Esempio: Gol dall'area piccola difesa, centrale

		Zone Predilette:
			Area centrale dell'campo dove può mostrarsi decisamente dominante.
			Esempio: Centrale

In [139]:
p='331422.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Mile Svilar

        	Mile Svilar:
			- Caratteristiche:
				Sviluppo fisico elevato, grande resistenza atletica, eccellenti capacità di parate, ottima visione di squadra, buona precisione nei passaggi corti, abilità nella gestione della palla sotto pressione.
			- Punti di Forza:
				Gestisce bene situazioni critiche, ha una forte personalità sul terreno di gioco, si adatta facilmente alle diverse posizioni all'interno dell'organizzazione tattica della sua squadra.
			- Debolezze:
				Possiede una certa rigidità nelle sue mosse, può avere difficoltà a reagire rapidamente ai cambiamenti improvvisi negli schemi offensivi degli avversari.
			- Zone Predilette:
				Difende principalmente l'area centrale dello schema organizzativo della propria squadra, ma anche occasionalmente gli estremi laterali se necessario.

*Difensori*

In [141]:
p='95408.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Virgil van Dijk

        	###Virgil van Dijk###
			####Characteristics####
				Virgil van Dijk is an experienced defender with excellent aerial ability and strong leadership skills. He has been praised by many as one of the best center backs currently playing football today due to his physicality, strength, and tactical awareness on both sides of defense. His presence at the back line allows him to read plays quickly while also being able to make crucial interceptions when needed most. Additionally, Van Dyk possesses great composure under pressure which helps keep opponents from scoring goals easily against him or other defenders around him during games.
			####Strengths####
				The main strengths that stand out about this player include but aren't limited too;
					a) Aerial dominance – This means he excels at heading balls away from danger zones near goal area especially if they're coming towards netting direction (goalkeeper). It makes it harder opponent team trying score because there won’t be any chance left open after successful clearances made by VVD himself!
					b) Strong tackling abilities– With powerful legs combined alongside quick reflexes, no wonder why so few players manage get past him without getting tackled down first! Even though sometimes these tackles may seem harsher than necessary depending upon situation itself however overall effectiveness remains high throughout entire match duration regardless what happens next moment later...
					c) Leadership qualities- As captain leader figure within squad since long time ago now everyone knows exactly who leads charge whenever something needs done right way possible given circumstances present themselves before eyesight alone cannot provide enough information required making correct decisions accordingly afterwards resulting into better results achieved ultimately leading success stories behind scenes nobody else ever gets credit deservedly earned through hard work dedication commitment shown everyday despite facing numerous challenges along journey ahead reaching ultimate destination desired outcome sought after all along finally reached once again proving oneself worthy deserving recognition received rightfully deserved based solely off merits displayed consistently over extended period lasting several years continuously improving year after another until perfect masterpiece created eventually unveiled world ready enjoy marveling beauty contained inside such magnificent creation brought forth existence thanks entirely efforts put forward collectively working together harmoniously striving reach common goal shared amongst members group united cause greater good society benefit humanity large scale level impacting positively lives millions people across globe simultaneously bringing joy happiness smiles faces everywhere leaving indelible mark history books forevermore remembered fondly cherished deeply treasured highly valued beyond measure immeasurable value priceless worthlessness incomparable rarity uniqueness unmatched quality unrivalled excellence unparalleled brilliance unsurpassed perfection absolute mastery complete control total domination supreme

In [142]:
p='349406.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Nicolò Casale

        	Nicolò Casale

			**Caratteristiche**

				Giocatore molto abile nella fase offensiva, capace di creare occasioni decisive grazie alla sua visione di gioco ed al controllo palla.
				Efficiente nelle fasi finalizzanti, dotato di buona precisione nei passaggi lunghi e precisi.

			**Punti di Forza**

				Passaggio accurato e rapido; capacità di vedere gli spazi aperti sul terreno di gioco; velocità di movimento;
				capacità di dribbling; potenza fisica;

			**Debolezze**

				Mancanza di resistenza ai colpi duri; scarsa reattività alle situazioni critiche; mancanza di padronanza della palla sotto pressione;


			**Zona Prediletta**

				Centrocampo e area di rigore

In [144]:
p='69778.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Kyle Walker

*Centrocampisti*

In [145]:
p='332325.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Declan Rice

        	Declan Rice:
	        Caratteristiche:
	            Tecnico Tatticamente versatili, abilmente si muove tra diverse posizioni sul terreno di gioco,
	                adatta al ruolo di mediano centrale ma anche quello di esterno destro o interno.
	            Attento ai passaggi precisi, efficace nelle ripartenze dalla linea difensiva ed efficiente nella creazione
	                di occasioni offensive grazie alle sue qualità di visione e controllo palla.
	        Punti di Forza:
	            Passaggi precisi e creativi, capacità di leggere lo sviluppo della partita e reagire tempestivamente,
	                buona resistenza fisica permette di mantenere costantemente alta intensità nei momenti cruciali.
	        Debolezze:
	            In alcuni casi può esagerare negli schemi di gioco preferendo soluzioni troppo prevedibili rispetto all'imprevedibilità necessaria
	                per cogliere gli errori avversari.
	        Zone Predilette:
	            Centrocampo, zona di riapertura, area di rigore.

In [146]:
p='343382.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Tijjani Reijnders

        	Tijjani Reijnders

		Caratteristiche:
			Giocatore versatile capace di adattarsi alle diverse situazioni sul terreno di gioco.
			Dotato di una buona visione di squadra ed abilità nella lettura della posizione degli avversari.
			Molto bravo nei passaggi precisi sia lunghi che corti.

		Punti di Forza:
			Eccellenti capacità di controllo palla e dribbling.
			Buone doti atletiche e velocità.
			Abitudine al contatto fisico e all'impatto con gli altri giocatori.

		Debolezze:
			Necessita di lavorare sulla sua resistenza e potenziamento muscolare.
			Rischio di perdere possesso quando si trova sotto pressione.
			Sviluppare maggior consapevolezza strategica nelle fasi finali dell'incontro.

		Zone del Campo Predilette:
			Laterale destro e centrocampo centrale.

In [147]:
p='302691.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Remo Freuler

        	Remo Freuler:
			Caratteristiche:
				Frequenza elevata di passaggi chiavi dalla zona della punizione al terzo quarto dell'area difensiva.
				Elevate percentuali di successo nei passaggi chiavi verso entrambi gli estremi del campo.
				Possiede buone capacità di creare occasioni nella metà campo avversaria attraverso passaggi precisi ed efficaci.
				Sviluppa anche abilità offensive nelle fasi finali degli sviluppi offensivi.
				Molto bravo ad anticipare situazioni critiche e prevenire errori negli scambi con altri compagni.
				Risulta particolarmente efficiente quando si trova in posizioni centrali sul campo.
				Dotato di ottima visione di gioco e capacità di individuare spazi vuoti tra le linee difensive avverse.
				In grado di gestire bene le pressioni opposte dai marcatori avversari.
				Grazie alle sue doti atletiche può superare facilmente i marcatore e raggiungere lo spazio aperto.
				Ben disposto a correre fino all'esterno dello schema di gioco per aiutare la squadra a recuperare palla.
				Vantaggioso sotto tutti aspetti sia in fase difensiva che offensiva.
			Punti di Forza:
				Ottimo controllo di palla.
				Abitudine a prendere decisioni rapide e accurate sulla base della situazione presente sul campo.
				Buona conoscenza strategica del gioco.
				Abbastanza veloce e agile per evitare i marcatori.
				Brillanti qualità di ricezione e precisione nei passaggi.
				Impressionante intelligenza tattica.
				Grande determinazione e volontà di vincere.
				Tendeva a colpire forte ma accuratamente.
			Debolezze:
				Poca resistenza fisica.
				Necessita di allenamento regolare per mantenere forma e condizione.
				Non sempre riesce a trovare soluzioni creative per uscire dalle difficoltà.
				Qualche volta tende a perdere la calma in momenti critici

*Attaccanti*

In [148]:
p='349207.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Rafael Leão

        	Rafael Leão

        	Caratteristiche:
        		- Tecnica precisa nei calci d'angolo e nelle punizioni dirette dalla linea degli undici metri.
        		- Velocità elevata nella corsa al pallone.
        		- Capacità di dribbling rapido ed efficace.

        	Punti di Forza:
        		- Tiro potente da lunga distanza.
        		- Controllo palla preciso anche sotto pressione avversaria.
        		- Creatività individuale quando si trova davanti all'avversario.

        	Debolezze:
        		- Difficoltà ad inserirsi negli spazi tra gli avversari.
        		- Poca capacità di visione globale della situazione sul terreno di gioco.
        		- Scarsa resistenza fisica.

        	Zona Prediletta:
        		- Centrocampo.

In [149]:
p='383956.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Joshua Zirkzee

        	###Joshua Zirkzee
        	####Caratteristiche:
        		Eseguendo una serie di azioni diverse, si può notare che Joshua Zirkzee ha dimostrato di avere buoni riflessi, capacità di anticipazione e abilità nella gestione del traffico.
                Inoltre, mostra anche una certa padronanza nei movimenti laterali ed esterni, grazie alla sua velocità e agilità.
                ####Punti di Forza:
                    La maggior parte degli elementi positivi sono legati al suo repertorio offensivo,
                        tra cui dribblature efficaci, passaggi precisi e tiri potenti dalla distanza.
                        Tuttavia, nonostante sia dotato di queste qualità positive, sembra mancare qualche elemento fondamentale nelle sue prestazioni difensive.
                            Ad esempio, quando viene affrontato da avversari veloci oppure quando deve contrastare giocatori alti,
                                tende ad arrendersi troppo facilmente senza tentare alcuna reazione adeguata.
                                    Questo lo rende vulnerabile alle incursioni nemiche e diminuisce la sua efficacia sul terreno di gioco.
                                        Per questo motivo, dovrebbe lavorare sulla propria resistenza fisica e sui suoi meccanismi di copertura difensiva.
                                            Altrimenti rischia di perdere molta competitività contro squadre ben organizzate e solide difensive.
                                                ####Zona Prediletto:
                                                    Dalle statistiche emerge che Joshua Zirkzee preferisce operare principalmente all'esterno dello schema di gioco,
                                                        dove riesce a mettere in difficoltà gli avversari attraverso rapide finte e scambi rapidissimi.
                                                            Quando invece entra in area, generalmente cerca di evitare conflitti diretti ma piuttosto favorisce interventi indiretti tramite assist intelligentemente posizionati.
                                                                Ciò permette allo stesso tempo di mantenere alta la tensione psicologica negli avversari mentre crea occasioni per altri compagni d'equippe.
                                                                    Infine, sebbene non sia particolarmente bravo sotto porta, riusciamo comunque a vedere alcuni momenti decisivi segnando gol importanti proprio grazie

In [150]:
p='480249.0'
print(desc[p]['name'])
#print(desc[p].keys())
j=0
for line in desc[p]['description'].split('\n'):
    if j >= 0:
        print(line)
    
    j+=1

Lamine Yamal

        	Lamine Yamal:
        	- Caratteristiche:
        		- Tecnica elevata nella fase finale d'attacco;
        		- Buona visione di gioco;
        		- Velocità e agilità notevoli;

        	Punti di Forza:
        		- Tiri dalla distanza ravvicinata;
        		- Assist efficaci nelle fasi finali;
        		- Parate potenti ed accurate;

        	Debolezze:
        		- Difficoltà ad anticipare gli avversari rapidamente;
        		- Problemi di controllo palla nei momenti cruciali;

        	Zone Predilette:
        		- Centrocampo;
        		- Area Piccola Attacco;

In [23]:
import os
import utils 
def getPlayersDict(path: str, season: str = None ) -> dict:
    players_list = {}
    #for file in os.listdir(path):
    for file in os.listdir(path):
        nazione = file.split('-')[0]
        if season != None:
            elab_file = season in file
            print(season,file, elab_file)
        else:
            elab_file = True
        dict_file = utils.readJson(f'{path}/{file}')
        for row in dict_file.values():
            if nazione != 'Europa':
                players_list = players_list | row['players']
            #players_list = players_list + players
    #players_list = [float(player) if '.' in player else int(player) for player in players_list]
    players_list.pop('0.0')

    return players_list

getPlayersDict('Dataset/Events2Text/TeamPlayerList', '2023-2024')

2023-2024 Europa-Champions-League_2019-2020_teams.json False
2023-2024 Europa-Champions-League_2020-2021_teams.json False
2023-2024 Europa-Champions-League_2021-2022_teams.json False
2023-2024 Europa-Champions-League_2022-2023_teams.json False
2023-2024 Europa-Champions-League_2023-2024_teams.json True
2023-2024 Europa-Europa-League_2019-2020_teams.json False
2023-2024 Europa-Europa-League_2020-2021_teams.json False
2023-2024 Europa-Europa-League_2021-2022_teams.json False
2023-2024 Europa-Europa-League_2022-2023_teams.json False
2023-2024 Europa-Europa-League_2023-2024_teams.json True
2023-2024 Francia-Ligue-1_2019-2020_teams.json False
2023-2024 Francia-Ligue-1_2020-2021_teams.json False
2023-2024 Francia-Ligue-1_2021-2022_teams.json False
2023-2024 Francia-Ligue-1_2022-2023_teams.json False
2023-2024 Francia-Ligue-1_2023-2024_teams.json True
2023-2024 Germania-Bundesliga_2019-2020_teams.json False
2023-2024 Germania-Bundesliga_2020-2021_teams.json False
2023-2024 Germania-Bundesliga_2021-2022_teams.json False
2023-2024 Germania-Bundesliga_2022-2023_teams.json False
2023-2024 Germania-Bundesliga_2023-2024_teams.json True
2023-2024 Inghilterra-Premier-League_2019-2020_teams.json False
2023-2024 Inghilterra-Premier-League_2020-2021_teams.json False
2023-2024 Inghilterra-Premier-League_2021-2022_teams.json False
2023-2024 Inghilterra-Premier-League_2022-2023_teams.json False
2023-2024 Inghilterra-Premier-League_2023-2024_teams.json True
2023-2024 Italia-Serie-A_2019-2020_teams.json False
2023-2024 Italia-Serie-A_2020-2021_teams.json False
2023-2024 Italia-Serie-A_2021-2022_teams.json False
2023-2024 Italia-Serie-A_2022-2023_teams.json False
2023-2024 Italia-Serie-A_2023-2024_teams.json True
2023-2024 Paesi-Bassi-Eredivisie_2019-2020_teams.json False
2023-2024 Paesi-Bassi-Eredivisie_2020-2021_teams.json False
2023-2024 Paesi-Bassi-Eredivisie_2021-2022_teams.json False
2023-2024 Paesi-Bassi-Eredivisie_2022-2023_teams.json False
2023-2024 Paesi-Bassi-Eredivisie_2023-2024_teams.json True
2023-2024 Portogallo-Liga-Portugal_2019-2020_teams.json False
2023-2024 Portogallo-Liga-Portugal_2020-2021_teams.json False
2023-2024 Portogallo-Liga-Portugal_2021-2022_teams.json False
2023-2024 Portogallo-Liga-Portugal_2022-2023_teams.json False
2023-2024 Portogallo-Liga-Portugal_2023-2024_teams.json True
2023-2024 Spagna-LaLiga_2019-2020_teams.json False
2023-2024 Spagna-LaLiga_2020-2021_teams.json False
2023-2024 Spagna-LaLiga_2021-2022_teams.json False
2023-2024 Spagna-LaLiga_2022-2023_teams.json False
2023-2024 Spagna-LaLiga_2023-2024_teams.json True

{'365122.0': 'Boulaye Dia',
 '21073.0': 'Jacques-Alaixys Romao',
 '234352.0': 'Yunis Abdelhamid',
 '135061.0': 'Predrag Rajkovic',
 '300426.0': 'Axel Disasi',
 '115882.0': 'Thomas Foket',
 '108334.0': 'Tristan Dingomé',
 '236556.0': 'Xavier Chavalerin',
 '234346.0': 'Moussa Doumbia',
 '239881.0': 'Hassane Kamara',
 '322421.0': 'Rémi Oudin',
 '380614.0': 'Nathanaël Mbuku',
 '83383.0': 'Suk Hyun-Jun',
 '331567.0': 'Ghislain Konan',
 '372721.0': 'Timothé Nkada',
 '377411.0': 'Marshall Munetsi',
 '261779.0': 'Dereck Kutesa',
 '297211.0': 'Mathieu Cafaro',
 '261267.0': 'Anastasios Donis',
 '380615.0': 'Sambou Sissoko',
 '373460.0': 'Moreto Cassamá',
 '391527.0': 'El Bilal Touré',
 '355134.0': 'Kaj Sierhuis',
 '275036.0': 'Nicolas Lemaître',
 '144285.0': 'Arbër Zeneli',
 '377270.0': 'Dario Maresic',
 '251134.0': 'Duje Caleta-Car',
 '14058.0': 'Dimitri Payet',
 '134902.0': 'Jordan Amavi',
 '93917.0': 'Valère Germain',
 '35954.0': 'Kevin Strootman',
 '62108.0': 'Hiroki Sakai',
 '302441.0': 'Nemanja Radonjic',
 '29545.0': 'Steve Mandanda',
 '331790.0': 'Boubacar Kamara',
 '115508.0': 'Morgan Sanson',
 '43369.0': 'Luiz Gustavo',
 '104747.0': 'Bouna Sarr',
 '125262.0': 'Darío Benedetto',
 '365193.0': 'Florian Chabrolle',
 '99907.0': 'Álvaro González',
 '288883.0': 'Maxime Lopez',
 '99143.0': 'Florian Thauvin',
 '296342.0': 'Saîf-Eddine Khaoui',
 '231144.0': 'Valentin Rongier',
 '375340.0': 'Lucas Perrin',
 '380613.0': 'Isaac Lihadji',
 '383628.0': 'Marley Aké',
 '19845.0': 'Yohann Pelé',
 '236520.0': 'Mickaël Le Bihan',
 '123873.0': 'Wylan Cyprien',
 '329246.0': 'Patrick Burner',
 '6683.0': 'Dante',
 '347815.0': 'Yannis Clémentia',
 '112220.0': 'Christophe Hérelle',
 '344645.0': 'Ignatius Ganago',
 '124721.0': 'Adrien Tameze',
 '125326.0': 'Rémi Walter',
 '322747.0': 'Malang Sarr',
 '336074.0': 'Myziane Maolida',
 '368271.0': 'Eddy Sylvestre',
 '333437.0': 'Bassem Srarfi',
 '318485.0': 'Ihsan Sacko',
 '236515.0': 'Arnaud Lusamba',
 '147810.0': 'Racine Coly',
 '301243.0': 'Pierre Lees-Melou',
 '351344.0': 'Andy Pelmard',
 '381664.0': 'Ibrahim Cissé',
 '366379.0': 'Khéphren Thuram',
 '130304.0': 'Walter Benítez',
 '361816.0': 'Youcef Atal',
 '123253.0': 'Gautier Lloris',
 '297577.0': 'Adam Ounas',
 '349755.0': 'Stanley Nsoki',
 '322163.0': 'Kasper Dolberg',
 '327905.0': 'Alexis Claude-Maurice',
 '377583.0': 'Hicham Boudaoui',
 '294056.0': 'Danilo Barbosa',
 '281010.0': 'Moussa Wagué',
 '283282.0': 'Riza Durmisi',
 '361890.0': 'Jordan Lefort',
 '303677.0': 'Cheick Timité',
 '295248.0': 'Haitam Aleesami',
 '334654.0': 'Juan Otero',
 '14240.0': 'Christophe Jallet',
 '256220.0': 'Alexis Blin',
 '236506.0': 'Serhou Guirassy',
 '101870.0': 'Prince-Désir Gouano',
 '100869.0': 'Thomas Monconduit',
 '110127.0': 'Eddy Gnahoré',
 '32167.0': 'Régis Gurtner',
 '301022.0': 'Chadrac Akolo',
 '320575.0': 'Saman Ghoddos',
 '139838.0': 'Bongani Zungu',
 '70291.0': 'Gaël Kakuta',
 '248278.0': 'Bakaye Dibassy',
 '380636.0': 'Madih Talal',
 '120755.0': 'Moussa Konaté',
 '243919.0': 'Arturo Calabresi',
 '261211.0': 'Quentin Cornette',
 '31713.0': 'Aurélien Chedjou',
 '332135.0': 'Fousseni Diabaté',
 '6476.0': 'Mathieu Bodmer',
 '279539.0': 'Steven Mendoza',
 '366839.0': 'Jack Lahne',
 '362546.0': 'Nicholas Opoku',
 '296317.0': 'Isaac Mbenza',
 '279380.0': 'Andrei Girotto',
 '44031.0': 'Fábio',
 '105339.0': 'Molla Wagué',
 '84899.0': 'Nicolas Pallois',
 '128880.0': 'Abdoulaye Touré',
 '302695.0': 'Charles Traoré',
 '256539.0': 'Marcus Coco',
 '102212.0': 'Lucas Lima',
 '107555.0': 'Kalifa Coulibaly',
 '300590.0': 'Alban Lafont',
 '342571.0': 'Samuel Moutoussamy',
 '380713.0': 'Abdoul Kader Bamba',
 '109526.0': 'Mehdi Abeid',
 '367217.0': 'Imrân Louza',
 '202185.0': 'Moses Simon',
 '129310.0': 'Cristian Benavente',
 '299562.0': 'Ludovic Blas',
 '91088.0': 'Dennis Appiah',
 '73948.0': 'Rene Krhin',
 '362435.0': 'Thomas Basila',
 '367413.0': 'Élie Youan',
 '262414.0': 'Roli Pereira De Sa',
 '133439.0': 'Renaud Emond',
 '361766.0': 'Percy Ruiz',
 '27973.0': 'Denis Petric',
 '386167.0': 'Wesley Moustache',
 '370004.0': 'Josué Homawoo',
 '92590.0': 'Anthony Limbombe',
 '377311.0': 'Domagoj Bradaric',
 '298510.0': 'Victor Osimhen',
 '241019.0': 'Jonathan Bamba',
 '43415.0': 'Benjamin André',
 '367181.0': 'Tiago Djaló',
 '19859.0': 'José Fonte',
 '345664.0': 'Boubakary Soumaré',
 '353991.0': 'Timothy Weah',
 '141646.0': 'Mike Maignan',
 '322094.0': 'Jonathan Ikoné',
 '136481.0': 'Zeki Çelik',
 '248121.0': 'Thiago Maia',
 '303158.0': 'Yusuf Yazici',
 '361812.0': 'Reinildo',
 '23054.0': 'Loïc Rémy',
 '334087.0': 'Gabriel Magalhães',
 '380711.0': 'Cheikh Niasse',
 '11895.0': 'Adama Soumaoro',
 '299450.0': 'Renato Sanches',
 '317743.0': 'Luiz Araújo',
 '42248.0': 'Jérémy Pied',
 '380712.0': 'Abou Ouattara',
 '329409.0': 'Xeka',
 '70735.0': 'Nicolás Gaitán',
 '392388.0': 'Jean Onana',
 '6890.0': 'Jimmy Briand',
 '78443.0': 'Nicolas de Préville',
 '91779.0': 'Pablo',
 '29586.0': 'Benoît Costil',
 '121720.0': 'Mexer',
 '312705.0': 'Samuel Kalu',
 '353423.0': 'Aurélien Tchouaméni',
 '127571.0': 'Hwang Ui-Jo',
 '372372.0': 'Albert Lottin',
 '242253.0': 'Loris Benito',
 '349184.0': 'Raoul Bellanova',
 '343982.0': 'Toma Basic',
 '372890.0': 'Yassine Benrahou',
 '325156.0': 'Josh Maja',
 '146764.0': 'Otávio',
 '42002.0': 'Youssouf Sabaly',
 '30051.0': 'Laurent Koscielny',
 '288891.0': 'Enock Kwateng',
 '357811.0': 'Yacine Adli',
 '244780.0': 'Vukasin Jovanovic',
 '231150.0': 'François Kamano',
 '296230.0': 'Youssef Bennasser',
 '279520.0': 'Jonathan Cafú',
 '115817.0': 'Maxime Poundjé',
 '354505.0': 'Gaëtan Poussin',
 '106887.0': 'Rubén Pardo',
 '69683.0': 'Mateo Pavlovic',
 '34212.0': 'Thomas Mangani',
 '234365.0': 'Vincent Manceau',
 '128361.0': 'Pierrick Capelle',
 '6740.0': 'Ludovic Butelle',
 '277239.0': 'Jeff Reine-Adélaïde',
 '236558.0': 'Baptiste Santamaría',
 '232577.0': 'Romain Thomas',
 '104746.0': 'Rachid Alioui',
 '355401.0': 'Rayan Aït-Nouri',
 '303314.0': 'Mathias Pereira Lage',
 '141154.0': 'Théo Pellenard',
 '362710.0': 'Farid El Melali',
 '90061.0': 'Vincent Pajot',
 '298542.0': 'Casimir Ninga',
 '344697.0': 'Wilfried Kanga',
 '101904.0': 'Stéphane Bahoken',
 '27356.0': 'Ismaël Traoré',
 '92531.0': 'Abdoulaye Bamba',
 '259809.0': 'Sada Thioub',
 '296316.0': 'Angelo Fulgini',
 '296221.0': 'Antonin Bobichon',
 '243066.0': 'Ibrahim Cissé',
 '110019.0': 'Danijel Petkovic',
 '328463.0': 'Souleyman Doumbia',
 '388730.0': 'Zinédine Ould Khaled',
 '69781.0': 'Gaëtan Charbonnier',
 '357101.0': 'Ibrahima Diallo',
 '316670.0': 'Samuel Grandsir',
 '331466.0': 'Romain Perraud',
 '239878.0': 'Dénys Bain',
 '239806.0': 'Jean-Charles Castelletto',
 '357534.0': 'Gautier Larsonneur',
 '38934.0': 'Julien Faussurier',
 '236553.0': 'Haris Belkebla',
 '83197.0': 'Mathias Autret',
 '234357.0': 'Yoann Court',
 '96703.0': 'Cristian Battocchio',
 '298930.0': "Ferris N'Goma",
 '109797.0': 'Kévin Mayi',
 '67425.0': 'Paul Lasne',
 '34011.0': 'Ludovic Baal',
 '130298.0': 'Brendan Chardonnet',
 '333419.0': 'Irvin Cardona',
 '288901.0': 'Alexandre Mendy',
 '105321.0': 'Donovan Léon',
 '296351.0': 'Gaëtan Belaud',
 '374992.0': 'Jean-Kévin Duverne',
 '330614.0': 'Hugo Magnetti',
 '387578.0': "Hianga'a Mbock",
 '34114.0': 'Mathieu Dossevi',
 '297210.0': 'Kelvin Amian',
 '366875.0': 'Bafodé Diakité',
 '334663.0': 'Agustín Rogel',
 '105028.0': 'Baptiste Reynet',
 '142403.0': 'Efthymios Koulouris',
 '328075.0': 'Ibrahim Sangaré',
 '300634.0': 'Jean-Victor Makengo',
 '29814.0': 'Max Gradel',
 '121858.0': 'Issiaga Sylla',
 '25565.0': 'William Vainqueur',
 '261992.0': 'Aaron Leya Iseka',
 '129648.0': 'Steven Moreira',
 '301247.0': 'Quentin Boisgard',
 '365124.0': 'Kalidou Sidibé',
 '129819.0': 'Wesley Saïd',
 '381653.0': 'Mathieu Gonçalves',
 '89947.0': 'Nicolas Isimat-Mirin',
 '100054.0': 'Gen Shoji',
 '83304.0': 'Yaya Sanogo',
 '369570.0': 'Manu Koné',
 '375342.0': 'Moussa Diarra',
 '118351.0': 'Corentin Jean',
 '375341.0': 'Nathan Ngoumou',
 '389409.0': 'Amine Adli',
 '247456.0': 'Ruben Gabrielsen',
 '139533.0': 'Lovre Kalinic',
 '391526.0': 'Adil Taoui',
 '391837.0': 'Janis Antiste',
 '90180.0': 'Mauro Goicoechea',
 '89935.0': 'Benjamin Jeannot',
 '361805.0': 'Senou Coulibaly',
 '42573.0': 'Bruno Ecuele Manga',
 '119779.0': 'Júlio Tavares',
 '296353.0': 'Mickaël Alphonse',
 '42577.0': 'Frédéric Sammaritano',
 '345396.0': 'Mama Baldé',
 '149599.0': 'Didier Ndong',
 '236500.0': 'Fouad Chafik',
 '70253.0': 'Romain Amalfitano',
 '141841.0': 'Rúnar Rúnarsson',
 '361806.0': 'Abdoulaye Jules Keita',
 '380643.0': 'Bryan Soumaré',
 '356704.0': 'Enzo Loiodice',
 '90117.0': 'Wesley Lautoa',
 '377421.0': 'Glody Ngonda',
 '380644.0': 'Rayan Philippe',
 '362434.0': 'Nayef Aguerd',
 '236559.0': 'Jordan Marié',
 '318750.0': 'Stephy Mavididi',
 '322494.0': 'Hamza Mendyl',
 '279541.0': 'Matheus Pereira',
 '9017.0': 'Florent Balmont',
 '97213.0': 'Alfred Gomis',
 '320245.0': 'Mounir Chouiar',
 '142819.0': 'Jhonder Cádiz',
 '387586.0': 'Ahmad Ngouyamsa',
 '114168.0': 'Yassine Benzia',
 '97813.0': 'Miguel Trauco',
 '139111.0': 'Jean-Eudes Aholou',
 '78023.0': 'Romain Hamouma',
 '279169.0': 'Harold Moukoudi',
 '11367.0': 'Mathieu Debuchy',
 '25608.0': 'Stéphane Ruffier',
 '13436.0': 'Loic Perrin',
 '33886.0': "Yann M'Vila",
 '71381.0': 'Wahbi Khazri',
 '67958.0': 'Ryad Boudebouz',
 '249857.0': 'Dénis Bouanga',
 '330832.0': 'Zaydou Youssouf',
 '328288.0': 'Arnaud Nordin',
 '69499.0': 'Robert Beric',
 '44417.0': 'Timothée Kolodziejczak',
 '232587.0': 'Lois Diony',
 '362498.0': 'Sergi Palencia',
 '12376.0': 'Yohan Cabaye',
 '367963.0': 'Charles Abi',
 '384106.0': 'Stefan Bajic',
 '35249.0': 'Jessy Moulin',
 '361822.0': 'William Saliba',
 '373946.0': 'Wesley Fofana',
 '86684.0': 'Gabriel Silva',
 '137837.0': 'Franck Honorat',
 '349960.0': 'Mahdi Camara',
 '260588.0': 'Assane Dioussé',
 '373167.0': 'Bilal Benkhedim',
 '388534.0': 'Edmilson Indjai Correia',
 '390758.0': 'Maxence Rivera',
 '391839.0': 'Yvann Maçon',
 '371447.0': 'Lyle Foster',
 '8040.0': 'Cesc Fàbregas',
 '296769.0': 'Benjamin Henrichs',
 '44208.0': 'Kamil Glik',
 '365641.0': 'Jonathan Panzo',
 '89928.0': 'Benjamin Lecomte',
 '328968.0': 'Fodé Ballo-Touré',
 '296576.0': 'Gelson Martins',
 '236546.0': 'Ruben Aguilar',
 '127970.0': 'Rony Lopes',
 '130435.0': 'Jemerson',
 '10714.0': 'Diego Benaglio',
 '146765.0': 'Boschilia',
 '244297.0': 'Adama Traoré',
 '344041.0': 'Moussa Sylla',
 '345409.0': 'Henry Onyekuru',
 '244560.0': 'Aleksandr Golovin',
 '89946.0': 'Wissam Ben Yedder',
 '365406.0': 'Benoît Badiashile',
 '136294.0': 'Keita Baldé',
 '299375.0': 'Gil Dias',
 '108055.0': 'Islam Slimani',
 '32598.0': 'Adrien Silva',
 '121417.0': 'Guillermo Maripán',
 '135211.0': 'Tiémoué Bakayoko',
 '245643.0': 'Jean-Kévin Augustin',
 '29214.0': 'Danijel Subasic',
 '29072.0': 'Stevan Jovetic',
 '362470.0': 'Youssouf Fofana',
 '322096.0': 'Houssem Aouar',
 '117776.0': 'Thiago Mendes',
 '300705.0': 'Lucas Tousart',
 '110154.0': 'Memphis Depay',
 '109807.0': 'Bertrand Traoré',
 '231135.0': 'Joachim Andersen',
 '143193.0': 'Youssouf Koné',
 '146724.0': 'Léo Dubois',
 '71833.0': 'Anthony Lopes',
 '243511.0': 'Jason Denayer',
 '140090.0': 'Moussa Dembélé',
 '355659.0': 'Jean Lucas',
 '125004.0': 'Maxwel Cornet',
 '145996.0': 'Kenny Tete',
 '329356.0': 'Martin Terrier',
 '27761.0': 'Marcelo',
 '354072.0': 'Oumar Solet',
 '121718.0': 'Marçal',
 '4092.0': 'Rafael',
 '386153.0': 'Rayan Cherki',
 '368272.0': 'Maxence Caqueret',
 '389064.0': 'Melvin Bard',
 '32676.0': 'Ciprian Tatarusanu',
 '236504.0': 'Karl Toko-Ekambi',
 '338780.0': 'Bruno Guimarães',
 '348654.0': 'Amine Gouiri',
 '79976.0': 'Andy Delort',
 '6743.0': 'Hilton',
 '67474.0': 'Pedro Mendes',
 '95422.0': 'Jordan Ferri',
 '80465.0': 'Arnaud Souquet',
 '13343.0': 'Daniel Congré',
 '74789.0': 'Damien Le Tallec',
 '140051.0': 'Gaëtan Laborde',
 '380645.0': 'Joris Chotard',
 '278191.0': 'Dimitry Bertaud',
 '244778.0': 'Mihailo Ristic',
 '125457.0': 'Keagan Dolly',
 '248017.0': 'Petar Skuletic',
 '2794.0': 'Souleymane Camara',
 '179014.0': 'Ambroise Oyongo',
 '125375.0': 'Gerónimo Rulli',
 '114169.0': 'Florent Mollet',
 '342540.0': 'Nicolas Cozza',
 '243069.0': 'Junior Sambia',
 '369413.0': 'Mathías Suárez',
 '234377.0': 'Téji Savanier',
 '386611.0': 'Bastian Badu',
 '137174.0': 'Yun Il-Lok',
 '391287.0': 'Thibaut Vargas',
 '256226.0': 'Bilal Boutobba',
 '387159.0': 'Clément Vidal',
 '367414.0': 'Matis Carvalho',
 '29590.0': 'Romain Salin',
 '297540.0': 'Jérémy Gélin',
 '58761.0': "M'Baye Niang",
 '79562.0': 'Clément Grenier',
 '332144.0': 'James Léa Siliki',
 '289018.0': 'Hamari Traoré',
 '296232.0': 'Faitout Maouassa',
 '369109.0': 'Eduardo Camavinga',
 '296241.0': 'Flavien Tait',
 '34176.0': 'Damien Da Silva',
 '22115.0': 'Jérémy Morel',
 '260812.0': 'Jordan Siebatcheu',
 '372280.0': 'Sacha Boey',
 '345386.0': 'Gerzino Nyamsi',
 '300291.0': 'Romain Del Castillo',
 '129282.0': 'Benjamin Bourigeaud',
 '321390.0': 'Édouard Mendy',
 '129999.0': 'Adrien Hunou',
 '300447.0': 'Raphinha',
 '92792.0': 'Jonas Martin',
 '298545.0': 'Joris Gnagnon',
 '361815.0': 'Yann Gboho',
 '357533.0': 'Rafik Guitane',
 '379615.0': 'Lucas da Cunha',
 '39935.0': 'Steven Nzonzi',
 '232582.0': 'Renaud Ripart',
 '234369.0': 'Anthony Briançon',
 '234405.0': 'Pablo Martinez',
 '143317.0': 'Zinedine Ferhat',
 '301047.0': 'Gaëtan Paquiez',
 '316029.0': 'Sofiane Alakouch',
 '234373.0': 'Théo Valls',
 '296340.0': 'Florian Miguel',
 '236563.0': 'Romain Philippoteaux',
 '288896.0': 'Paul Bernardoni',
 '318298.0': 'Haris Duljevic',
 '78041.0': 'Pierrick Valdivia',
 '372720.0': 'Théo Sainte-Luce',
 '381662.0': 'Sidy Sarr',
 '381663.0': 'Vlatko Stojanovski',
 '319464.0': 'Lamine Fomba',
 '35562.0': 'Lucas Deaux',
 '94932.0': 'Loïck Landre',
 '332814.0': 'Kévin Denkey',
 '335009.0': 'Sami Ben Amar',
 '330806.0': 'Lucas Dias',
 '363569.0': 'Lucas Buadés',
 '383564.0': 'Antoine Valério',
 '389063.0': 'Lucas Valls',
 '44609.0': 'Nolan Roux',
 '328436.0': 'Moussa Koné',
 '255167.0': 'Thilo Kehrer',
 '248112.0': 'Abdou Diallo',
 '28550.0': 'Thiago Silva',
 '96449.0': 'Julian Draxler',
 '101949.0': 'Marquinhos',
 '106894.0': 'Juan Bernat',
 '300713.0': 'Kylian Mbappé',
 '91961.0': 'Marco Verratti',
 '94868.0': 'Pablo Sarabia',
 '24328.0': 'Edinson Cavani',
 '92516.0': 'Alphonse Areola',
 '23110.0': 'Ángel Di María',
 '104376.0': 'Thomas Meunier',
 '93700.0': 'Leandro Paredes',
 '361283.0': 'Colin Dagba',
 '80464.0': 'Idrissa Gueye',
 '29809.0': 'Eric Choupo-Moting',
 '373556.0': 'Arthur Zagré',
 '382491.0': 'Adil Aouchiche',
 '361433.0': 'Marcin Bulka',
 '92795.0': 'Layvin Kurzawa',
 '106028.0': 'Jesé',
 '50835.0': 'Neymar',
 '65901.0': 'Keylor Navas',
 '106964.0': 'Mauro Icardi',
 '71174.0': 'Ander Herrera',
 '247800.0': 'Presnel Kimpembe',
 '373555.0': 'Loïc Mbe Soh',
 '109338.0': 'Sergio Rico',
 '382492.0': 'Tanguy Nianzou',
 '352830.0': 'Mitchel Bakker',
 '296372.0': 'Habib Diallo',
 '323211.0': 'Habib Maïga',
 '101911.0': 'Thomas Delaine',
 '323147.0': 'Mamadou Fofana',
 '34008.0': 'Alexandre Oukidja',
 '115837.0': 'Opa Nguette',
 '11908.0': 'Renaud Cohade',
 '298733.0': "Kévin N'Doram",
 '294496.0': 'Fabien Centonze',
 '294501.0': 'Farid Boulaya',
 '141592.0': 'Stoppila Sunzu',
 '342542.0': 'Ibrahima Niane',
 '259434.0': 'Marvin Gakpa',
 '285812.0': 'Victorien Angban',
 '67370.0': 'John Boye',
 '256844.0': 'Thierry Ambrose',
 '295590.0': 'Manuel Cabit',
 '286443.0': 'Matthieu Udol',
 '234388.0': 'Paul Delecroix',
 '389020.0': 'Georges Mikautadze',
 '321150.0': 'Dylan Bronn',
 '391288.0': 'Papa Yade',
 '121711.0': 'Alexander Djiku',
 '105151.0': 'Kenny Lala',
 '90446.0': 'Lionel Carole',
 '113747.0': 'Adrien Thomasson',
 '137720.0': 'Dimitri Liénard',
 '34214.0': 'Lamine Koné',
 '84041.0': 'Stefan Mitrovic',
 '234364.0': 'Ludovic Ajorque',
 '78386.0': 'Matz Sels',
 '320242.0': 'Jean-Ricner Bellegarde',
 '342550.0': 'Nuno da Costa',
 '344143.0': 'Kévin Zohi',
 '203216.0': 'Abdallah Ndour',
 '372855.0': 'Mohamed Simakan',
 '306766.0': 'Ibrahima Sissoko',
 '329620.0': 'Lebo Mothiba',
 '90107.0': 'Benjamin Corgnet',
 '361902.0': 'Moataz Zemzemi',
 '382159.0': 'Adrien Lebeau',
 '107891.0': 'Sanjin Prcic',
 '321145.0': 'Anthony Caci',
 '84462.0': 'Abdul Waris',
 '34116.0': 'Jeremy Grimm',
 '297409.0': 'Pedro Chirivella',
 '389937.0': 'Bridge Ndilu',
 '333542.0': 'Randal Kolo Muani',
 '391316.0': 'Batista Mendy',
 '71293.0': 'Sébastien Corchia',
 '410581.0': 'Abdoulaye Sylla',
 '27756.0': 'Paul Baysse',
 '388525.0': 'Mehdi Zerkane',
 '402130.0': 'Dilane Bakwa',
 '10194.0': 'Hatem Ben Arfa',
 '404404.0': 'Amadou Traoré',
 '408485.0': 'Tom Lacoux',
 '136262.0': 'Jean Seri',
 '410981.0': 'Issouf Sissokho',
 '402855.0': 'Sékou Mara',
 '369526.0': 'Loïc Bessilé',
 '320243.0': 'Enzo Ebosse',
 '288894.0': 'Lassana Coulibaly',
 '399014.0': 'Mohamed-Ali Cho',
 '123913.0': 'Jimmy Cabot',
 '118885.0': 'Ibrahim Amadou',
 '234363.0': 'Sofiane Boufal',
 '411935.0': 'Noah Fatar',
 '398229.0': 'Waniss Taïbi',
 '413679.0': 'Yassin Fortuné',
 '279511.0': 'Pape Cheikh',
 '372927.0': 'Junior Dina Ebimbe',
 '398226.0': 'Aurélien Scheidler',
 '362805.0': 'Alex Dobre',
 '141960.0': 'Aníbal Chalá',
 '300495.0': 'Bersant Celina',
 '146455.0': 'Roger Assalé',
 '400213.0': 'Wilitty Younoussa',
 '296328.0': 'Saturnin Allagbé',
 '357098.0': 'Anthony Racioppi',
 '243076.0': 'Aboubakar Kamara',
 '413349.0': 'Jacques Siwe',
 '415924.0': 'Erwan Belhadji',
 '416241.0': 'Charles Costes',
 '37379.0': 'Eiji Kawashima',
 '398395.0': 'Mehdi Chahiri',
 '82781.0': 'Idriss Saadi',
 '236555.0': 'Bingourou Kamara',
 '345648.0': 'Ismaël Aaneba',
 '404403.0': 'Mahamé Siby',
 '260493.0': 'Frédéric Guilbert',
 '412905.0': 'Moïse Sahi',
 '294502.0': 'Julien Laporte',
 '398392.0': 'Stéphane Diarra',
 '398393.0': 'Enzo Le Fée',
 '319474.0': 'Houboulang Mendes',
 '82350.0': 'Vincent Le Goff',
 '296240.0': 'Yoane Wissa',
 '108105.0': 'Paul Nardi',
 '33591.0': 'Fabien Lemoine',
 '285992.0': 'Adrian Grbic',
 '122346.0': 'Laurent Abergel',
 '398394.0': 'Franklin Wadja',
 '22618.0': 'Sylvain Marveaux',
 '328982.0': 'Pierre-Yves Hamel',
 '361813.0': 'Umut Bozok',
 '353292.0': 'Trevoh Chalobah',
 '69995.0': 'Thomas Fontaine',
 '89643.0': 'Jonathan Delaplace',
 '337825.0': 'Andreaw Gravillon',
 '400505.0': 'Terem Moffi',
 '355994.0': 'Armand Laurienté',
 '296228.0': 'Jérôme Hergault',
 '408263.0': 'Loris Mouyokolo',
 '29578.0': 'Matthieu Dreyer',
 '409556.0': 'Yoann Étienne',
 '23353.0': 'Yannick Cahuzac',
 '398416.0': 'Loïc Badé',
 '330672.0': 'Facundo Medina',
 '374993.0': 'Cheick Doucouré',
 '236552.0': 'Jonathan Gradit',
 '274934.0': 'Florian Sotoca',
 '328074.0': 'Clément Michelin',
 '34182.0': 'Jean-Louis Leca',
 '398417.0': 'Ismaël Boura',
 '300483.0': 'Simon Banza',
 '239595.0': 'Tony Mauricio',
 '234398.0': 'Manuel Perez',
 '301869.0': 'Jonathan Clauss',
 '236517.0': 'Steven Fortès',
 '254562.0': 'Seko Fofana',
 '94892.0': 'Massadio Haïdara',
 '403916.0': 'Aleksandar Radovanovic',
 '384005.0': 'Arnaud Kalimuendo',
 '283010.0': 'Wuilker Fariñez',
 '400193.0': 'David Pereira da Costa',
 '361823.0': 'Cheick Traoré',
 '413339.0': 'Ansou Sow',
 '413340.0': 'Adrien Louveau',
 '345527.0': 'Jordan Lotomba',
 '357138.0': 'Robson Bambu',
 '29544.0': 'Morgan Schneiderlin',
 '398414.0': 'Dan Ndoye',
 '382587.0': 'Evann Guessand',
 '393128.0': 'Alexis Trouillet',
 '398415.0': 'Flavius Daniliuc',
 '398949.0': 'Salim Ben Seghir',
 '342545.0': 'Hicham Mahou',
 '361710.0': 'Jean-Clair Todibo',
 '410258.0': 'Malik Sellouki',
 '398398.0': 'Jérémy Le Douaron',
 '300608.0': 'Ronaël Pierre-Gabriel',
 '349368.0': 'Romain Faivre',
 '361962.0': 'Heriberto Tavares',
 '135259.0': 'Steve Mounié',
 '398931.0': 'Lilian Brassier',
 '352920.0': 'Sébastien Cibois',
 '399771.0': 'Bandiougou Fadiga',
 '303656.0': 'Andrés Cubas',
 '320738.0': 'Birger Meling',
 '338366.0': 'Mattéo Ahlinvi',
 '128655.0': 'Niclas Eliasson',
 '403718.0': 'Karim Aribi',
 '400837.0': 'Marco Majouga',
 '372459.0': 'Kelyan Guessoum',
 '126292.0': 'Naomichi Ueda',
 '415275.0': 'Mahamadou Doucouré',
 '400838.0': 'Nassim Chadli',
 '254105.0': 'Clément Dépres',

In [48]:
def getTeamsPlayerDict(path: str) -> set:
    team_list = {}
    for file in os.listdir(path):
        nazione = file.split('-')[0]
        season = file.split('_')[1]
        if season not in team_list.keys():
            team_list[season] = {}

        dict_file = utils.readJson(f'{path}/{file}')

        for k, v in dict_file.items():
            if nazione != 'Europa':
                team_list[season][k] = v

    return team_list

getTeamsPlayerDict('Dataset/Events2Text/TeamPlayerList')

{'2019-2020': {'950': {'name': 'Reims',
   'players': {'365122.0': 'Boulaye Dia',
    '21073.0': 'Jacques-Alaixys Romao',
    '234352.0': 'Yunis Abdelhamid',
    '135061.0': 'Predrag Rajkovic',
    '300426.0': 'Axel Disasi',
    '115882.0': 'Thomas Foket',
    '108334.0': 'Tristan Dingomé',
    '236556.0': 'Xavier Chavalerin',
    '234346.0': 'Moussa Doumbia',
    '239881.0': 'Hassane Kamara',
    '322421.0': 'Rémi Oudin',
    '380614.0': 'Nathanaël Mbuku',
    '83383.0': 'Suk Hyun-Jun',
    '331567.0': 'Ghislain Konan',
    '372721.0': 'Timothé Nkada',
    '377411.0': 'Marshall Munetsi',
    '261779.0': 'Dereck Kutesa',
    '297211.0': 'Mathieu Cafaro',
    '261267.0': 'Anastasios Donis',
    '380615.0': 'Sambou Sissoko',
    '373460.0': 'Moreto Cassamá',
    '391527.0': 'El Bilal Touré',
    '355134.0': 'Kaj Sierhuis',
    '275036.0': 'Nicolas Lemaître',
    '144285.0': 'Arbër Zeneli',
    '377270.0': 'Dario Maresic'}},
  '249': {'name': 'Marseille',
   'players': {'251134.0': 'Duje Caleta-Car',
    '14058.0': 'Dimitri Payet',
    '134902.0': 'Jordan Amavi',
    '93917.0': 'Valère Germain',
    '35954.0': 'Kevin Strootman',
    '62108.0': 'Hiroki Sakai',
    '302441.0': 'Nemanja Radonjic',
    '29545.0': 'Steve Mandanda',
    '331790.0': 'Boubacar Kamara',
    '115508.0': 'Morgan Sanson',
    '43369.0': 'Luiz Gustavo',
    '104747.0': 'Bouna Sarr',
    '125262.0': 'Darío Benedetto',
    '365193.0': 'Florian Chabrolle',
    '99907.0': 'Álvaro González',
    '288883.0': 'Maxime Lopez',
    '99143.0': 'Florian Thauvin',
    '296342.0': 'Saîf-Eddine Khaoui',
    '231144.0': 'Valentin Rongier',
    '375340.0': 'Lucas Perrin',
    '380613.0': 'Isaac Lihadji',
    '383628.0': 'Marley Aké',
    '19845.0': 'Yohann Pelé'}},
  '613': {'name': 'Nice',
   'players': {'236520.0': 'Mickaël Le Bihan',
    '123873.0': 'Wylan Cyprien',
    '329246.0': 'Patrick Burner',
    '6683.0': 'Dante',
    '347815.0': 'Yannis Clémentia',
    '112220.0': 'Christophe Hérelle',
    '344645.0': 'Ignatius Ganago',
    '124721.0': 'Adrien Tameze',
    '125326.0': 'Rémi Walter',
    '322747.0': 'Malang Sarr',
    '336074.0': 'Myziane Maolida',
    '368271.0': 'Eddy Sylvestre',
    '333437.0': 'Bassem Srarfi',
    '318485.0': 'Ihsan Sacko',
    '236515.0': 'Arnaud Lusamba',
    '147810.0': 'Racine Coly',
    '301243.0': 'Pierre Lees-Melou',
    '351344.0': 'Andy Pelmard',
    '381664.0': 'Ibrahim Cissé',
    '366379.0': 'Khéphren Thuram',
    '130304.0': 'Walter Benítez',
    '361816.0': 'Youcef Atal',
    '123253.0': 'Gautier Lloris',
    '297577.0': 'Adam Ounas',
    '349755.0': 'Stanley Nsoki',
    '322163.0': 'Kasper Dolberg',
    '327905.0': 'Alexis Claude-Maurice',
    '377583.0': 'Hicham Boudaoui',
    '294056.0': 'Danilo Barbosa',
    '281010.0': 'Moussa Wagué',
    '283282.0': 'Riza Durmisi'}},
  '151': {'name': 'Amiens',
   'players': {'361890.0': 'Jordan Lefort',
    '303677.0': 'Cheick Timité',
    '295248.0': 'Haitam Aleesami',
    '334654.0': 'Juan Otero',
    '14240.0': 'Christophe Jallet',
    '256220.0': 'Alexis Blin',
    '236506.0': 'Serhou Guirassy',
    '101870.0': 'Prince-Désir Gouano',
    '100869.0': 'Thomas Monconduit',
    '110127.0': 'Eddy Gnahoré',
    '32167.0': 'Régis Gurtner',
    '301022.0': 'Chadrac Akolo',
    '320575.0': 'Saman Ghoddos',
    '139838.0': 'Bongani Zungu',
    '70291.0': 'Gaël Kakuta',
    '248278.0': 'Bakaye Dibassy',
    '380636.0': 'Madih Talal',
    '120755.0': 'Moussa Konaté',
    '243919.0': 'Arturo Calabresi',
    '261211.0': 'Quentin Cornette',
    '31713.0': 'Aurélien Chedjou',
    '332135.0': 'Fousseni Diabaté',
    '6476.0': 'Mathieu Bodmer',
    '279539.0': 'Steven Mendoza',
    '366839.0': 'Jack Lahne',
    '362546.0': 'Nicholas Opoku',
    '296317.0': 'Isaac Mbenza'}},
  '302': {'name': 'Nantes',
   'players': {'231144.0': 'Valentin Rongier',
    '279380.0': 'Andrei Girotto',
    '44031.0': 'Fábio',
    '105339.0': 'Molla Wagué',
    '84899.0': 'Nicolas Pallois',
    '128880.0': 'Abdoulaye Touré',
    '302695.0': 'Charles Traoré',
    '256539.0': 'Marcus Coco',
    '102212.0': 'Lucas Lima',
    '107555.0': 'Kalifa Coulibaly',
    '300590.0': 'Alban Lafont',
    '342571.0': 'Samuel Moutoussamy',
    '380713.0': 'Abdoul Kader Bamba',
    '109526.0': 'Mehdi Abeid',
    '367217.0': 'Imrân Louza',
    '202185.0': 'Moses Simon',
    '129310.0': 'Cristian Benavente',
    '299562.0': 'Ludovic Blas',
    '91088.0': 'Dennis Appiah',
    '73948.0': 'Rene Krhin',
    '362435.0': 'Thomas Basila',
    '367413.0': 'Élie Youan',
    '262414.0': 'Roli Pereira De Sa',
    '133439.0': 'Renaud Emond',
    '361766.0': 'Percy Ruiz',
    '27973.0': 'Denis Petric',
    '386167.0': 'Wesley Moustache',
    '370004.0': 'Josué Homawoo',
    '92590.0': 'Anthony Limbombe'}},
  '607': {'name': 'Lille',
   'players': {'377311.0': 'Domagoj Bradaric',
    '298510.0': 'Victor Osimhen',
    '241019.0': 'Jonathan Bamba',
    '43415.0': 'Benjamin André',
    '367181.0': 'Tiago Djaló',
    '19859.0': 'José Fonte',
    '345664.0': 'Boubakary Soumaré',
    '353991.0': 'Timothy Weah',
    '141646.0': 'Mike Maignan',
    '322094.0': 'Jonathan Ikoné',
    '136481.0': 'Zeki Çelik',
    '248121.0': 'Thiago Maia',
    '303158.0': 'Yusuf Yazici',
    '361812.0': 'Reinildo',
    '23054.0': 'Loïc Rémy',
    '334087.0': 'Gabriel Magalhães',
    '380711.0': 'Cheikh Niasse',
    '11895.0': 'Adama Soumaoro',
    '299450.0': 'Renato Sanches',
    '317743.0': 'Luiz Araújo',
    '42248.0': 'Jérémy Pied',
    '380712.0': 'Abou Ouattara',
    '329409.0': 'Xeka',
    '70735.0': 'Nicolás Gaitán',
    '392388.0': 'Jean Onana'}},
  '315': {'name': 'Bordeaux',
   'players': {'6890.0': 'Jimmy Briand',
    '78443.0': 'Nicolas de Préville',
    '91779.0': 'Pablo',
    '29586.0': 'Benoît Costil',
    '121720.0': 'Mexer',
    '312705.0': 'Samuel Kalu',
    '353423.0': 'Aurélien Tchouaméni',
    '127571.0': 'Hwang Ui-Jo',
    '372372.0': 'Albert Lottin',
    '242253.0': 'Loris Benito',
    '349184.0': 'Raoul Bellanova',
    '343982.0': 'Toma Basic',
    '372890.0': 'Yassine Benrahou',
    '325156.0': 'Josh Maja',
    '146764.0': 'Otávio',
    '42002.0': 'Youssouf Sabaly',
    '30051.0': 'Laurent Koscielny',
    '288891.0': 'Enock Kwateng',
    '357811.0': 'Yacine Adli',
    '244780.0': 'Vukasin Jovanovic',
    '231150.0': 'François Kamano',
    '296230.0': 'Youssef Bennasser',
    '279520.0': 'Jonathan Cafú',
    '115817.0': 'Maxime Poundjé',
    '322421.0': 'Rémi Oudin',
    '354505.0': 'Gaëtan Poussin',
    '106887.0': 'Rubén Pardo'}},
  '614': {'name': 'Angers',
   'players': {'69683.0': 'Mateo Pavlovic',
    '34212.0': 'Thomas Mangani',
    '234365.0': 'Vincent Manceau',
    '128361.0': 'Pierrick Capelle',
    '6740.0': 'Ludovic Butelle',
    '277239.0': 'Jeff Reine-Adélaïde',
    '236558.0': 'Baptiste Santamaría',
    '232577.0': 'Romain Thomas',
    '104746.0': 'Rachid Alioui',
    '355401.0': 'Rayan Aït-Nouri',
    '303314.0': 'Mathias Pereira Lage',
    '141154.0': 'Théo Pellenard',
    '362710.0': 'Farid El Melali',
    '90061.0': 'Vincent Pajot',
    '298542.0': 'Casimir Ninga',
    '344697.0': 'Wilfried Kanga',
    '101904.0': 'Stéphane Bahoken',
    '27356.0': 'Ismaël Traoré',
    '92531.0': 'Abdoulaye Bamba',
    '259809.0': 'Sada Thioub',
    '296316.0': 'Angelo Fulgini',
    '296221.0': 'Antonin Bobichon',
    '243066.0': 'Ibrahim Cissé',
    '110019.0': 'Danijel Petkovic',
    '328463.0': 'Souleyman Doumbia',
    '388730.0': 'Zinédine Ould Khaled'}},
  '2332': {'name': 'Brest',
   'players': {'69781.0': 'Gaëtan Charbonnier',
    '357101.0': 'Ibrahima Diallo',
    '316670.0': 'Samuel Grandsir',
    '331466.0': 'Romain Perraud',
    '239878.0': 'Dénys Bain',
    '239806.0': 'Jean-Charles Castelletto',
    '357534.0': 'Gautier Larsonneur',
    '38934.0': 'Julien Faussurier',
    '236553.0': 'Haris Belkebla',
    '83197.0': 'Mathias Autret',
    '234357.0': 'Yoann Court',
    '96703.0': 'Cristian Battocchio',
    '298930.0': "Ferris N'Goma",
    '109797.0': 'Kévin Mayi',
    '67425.0': 'Paul Lasne',
    '34011.0': 'Ludovic Baal',
    '130298.0': 'Brendan Chardonnet',
    '333419.0': 'Irvin Cardona',
    '288901.0': 'Alexandre Mendy',
    '105321.0': 'Donovan Léon',
    '296351.0': 'Gaëtan Belaud',
    '374992.0': 'Jean-Kévin Duverne',
    '330614.0': 'Hugo Magnetti',
    '387578.0': "Hianga'a Mbock"}},
  '246': {'name': 'Toulouse',
   'players': {'34114.0': 'Mathieu Dossevi',
    '297210.0': 'Kelvin Amian',
    '366875.0': 'Bafodé Diakité',
    '334663.0': 'Agustín Rogel',
    '105028.0': 'Baptiste Reynet',
    '142403.0': 'Efthymios Koulouris',
    '328075.0': 'Ibrahim Sangaré',
    '300634.0': 'Jean-Victor Makengo',
    '29814.0': 'Max Gradel',
    '121858.0': 'Issiaga Sylla',
    '25565.0': 'William Vainqueur',
    '261992.0': 'Aaron Leya Iseka',
    '129648.0': 'Steven Moreira',
    '301247.0': 'Quentin Boisgard',
    '365124.0': 'Kalidou Sidibé',
    '129819.0': 'Wesley Saïd',
    '381653.0': 'Mathieu Gonçalves',
    '89947.0': 'Nicolas Isimat-Mirin',
    '100054.0': 'Gen Shoji',
    '83304.0': 'Yaya Sanogo',
    '369570.0': 'Manu Koné',
    '375342.0': 'Moussa Diarra',
    '118351.0': 'Corentin Jean',
    '375341.0': 'Nathan Ngoumou',
    '389409.0': 'Amine Adli',
    '247456.0': 'Ruben Gabrielsen',
    '139533.0': 'Lovre Kalinic',
    '391526.0': 'Adil Taoui',
    '391837.0': 'Janis Antiste',
    '90180.0': 'Mauro Goicoechea'}},
  '1364': {'name': 'Dijon',
   'players': {'89935.0': 'Benjamin Jeannot',
    '361805.0': 'Senou Coulibaly',
    '42573.0': 'Bruno Ecuele Manga',
    '119779.0': 'Júlio Tavares',
    '296353.0': 'Mickaël Alphonse',
    '42577.0': 'Frédéric Sammaritano',
    '345396.0': 'Mama Baldé',
    '149599.0': 'Didier Ndong',
    '236500.0': 'Fouad Chafik',
    '70253.0': 'Romain Amalfitano',
    '141841.0': 'Rúnar Rúnarsson',
    '361806.0': 'Abdoulaye Jules Keita',
    '380643.0': 'Bryan Soumaré',
    '356704.0': 'Enzo Loiodice',
    '90117.0': 'Wesley Lautoa',
    '377421.0': 'Glody Ngonda',
    '380644.0': 'Rayan Philippe',
    '362434.0': 'Nayef Aguerd',
    '236559.0': 'Jordan Marié',
    '318750.0': 'Stephy Mavididi',
    '322494.0': 'Hamza Mendyl',
    '279541.0': 'Matheus Pereira',
    '9017.0': 'Florent Balmont',
    '97213.0': 'Alfred Gomis',
    '320245.0': 'Mounir Chouiar',
    '142819.0': 'Jhonder Cádiz',
    '387586.0': 'Ahmad Ngouyamsa',
    '114168.0': 'Yassine Benzia'}},
  '145': {'name': 'Saint-Etienne',
   'players': {'97813.0': 'Miguel Trauco',
    '139111.0': 'Jean-Eudes Aholou',
    '78023.0': 'Romain Hamouma',
    '279169.0': 'Harold Moukoudi',
    '11367.0': 'Mathieu Debuchy',
    '25608.0': 'Stéphane Ruffier',
    '13436.0': 'Loic Perrin',
    '33886.0': "Yann M'Vila",
    '71381.0': 'Wahbi Khazri',
    '67958.0': 'Ryad Boudebouz',
    '249857.0': 'Dénis Bouanga',
    '330832.0': 'Zaydou Youssouf',
    '328288.0': 'Arnaud Nordin',
    '69499.0': 'Robert Beric',
    '44417.0': 'Timothée Kolodziejczak',
    '232587.0': 'Lois Diony',
    '362498.0': 'Sergi Palencia',
    '12376.0': 'Yohan Cabaye',
    '367963.0': 'Charles Abi',
    '384106.0': 'Stefan Bajic',
    '35249.0': 'Jessy Moulin',
    '361822.0': 'William Saliba',
    '373946.0': 'Wesley Fofana',
    '86684.0': 'Gabriel Silva',
    '137837.0': 'Franck Honorat',
    '349960.0': 'Mahdi Camara',
    '260588.0': 'Assane Dioussé',
    '373167.0': 'Bilal Benkhedim',
    '388534.0': 'Edmilson Indjai Correia',
    '390758.0': 'Maxence Rivera',
    '391839.0': 'Yvann Maçon'}},
  '248': {'name': 'Monaco',
   'players': {'371447.0': 'Lyle Foster',
    '8040.0': 'Cesc Fàbregas',
    '296769.0': 'Benjamin Henrichs',
    '44208.0': 'Kamil Glik',
    '365641.0': 'Jonathan Panzo',
    '89928.0': 'Benjamin Lecomte',
    '328968.0': 'Fodé Ballo-Touré',
    '296576.0': 'Gelson Martins',
    '236546.0': 'Ruben Aguilar',
    '127970.0': 'Rony Lopes',
    '130435.0': 'Jemerson',
    '10714.0': 'Diego Benaglio',
    '146765.0': 'Boschilia',
    '244297.0': 'Adama Traoré',
    '344041.0': 'Moussa Sylla',
    '345409.0': 'Henry Onyekuru',
    '244560.0': 'Aleksandr Golovin',
    '89946.0': 'Wissam Ben Yedder',
    '365406.0': 'Benoît Badiashile',
    '136294.0': 'Keita Baldé',
    '299375.0': 'Gil Dias',
    '108055.0': 'Islam Slimani',
    '32598.0': 'Adrien Silva',
    '121417.0': 'Guillermo Maripán',
    '135211.0': 'Tiémoué Bakayoko',
    '245643.0': 'Jean-Kévin Augustin',
    '29214.0': 'Danijel Subasic',
    '29072.0': 'Stevan Jovetic',
    '362470.0': 'Youssouf Fofana',
    '353423.0': 'Aurélien Tchouaméni'}},
  '228': {'name': 'Lyon',
   'players': {'322096.0': 'Houssem Aouar',
    '117776.0': 'Thiago Mendes',
    '300705.0': 'Lucas Tousart',
    '110154.0': 'Memphis Depay',
    '109807.0': 'Bertrand Traoré',
    '231135.0': 'Joachim Andersen',
    '143193.0': 'Youssouf Koné',
    '146724.0': 'Léo Dubois',
    '71833.0': 'Anthony Lopes',
    '243511.0': 'Jason Denayer',
    '140090.0': 'Moussa Dembélé',
    '355659.0': 'Jean Lucas',
    '125004.0': 'Maxwel Cornet',
    '145996.0': 'Kenny Tete',
    '329356.0': 'Martin Terrier',
    '277239.0': 'Jeff Reine-Adélaïde',
    '27761.0': 'Marcelo',
    '354072.0': 'Oumar Solet',
    '121718.0': 'Marçal',
    '4092.0': 'Rafael',
    '386153.0': 'Rayan Cherki',
    '368272.0': 'Maxence Caqueret',
    '389064.0': 'Melvin Bard',
    '32676.0': 'Ciprian Tatarusanu',
    '236504.0': 'Karl Toko-Ekambi',
    '338780.0': 'Bruno Guimarães',
    '348654.0': 'Amine Gouiri'}},
  '311': {'name': 'Montpellier',
   'players': {'79976.0': 'Andy Delort',
    '6743.0': 'Hilton',
    '67474.0': 'Pedro Mendes',
    '95422.0': 'Jordan Ferri',
    '80465.0': 'Arnaud Souquet',
    '13343.0': 'Daniel Congré',
    '74789.0': 'Damien Le Tallec',
    '140051.0': 'Gaëtan Laborde',
    '380645.0': 'Joris Chotard',
    '278191.0': 'Dimitry Bertaud',
    '244778.0': 'Mihailo Ristic',
    '125457.0': 'Keagan Dolly',
    '248017.0': 'Petar Skuletic',
    '2794.0': 'Souleymane Camara',
    '179014.0': 'Ambroise Oyongo',
    '125375.0': 'Gerónimo Rulli',
    '114169.0': 'Florent Mollet',
    '342540.0': 'Nicolas Cozza',
    '243069.0': 'Junior Sambia',
    '369413.0': 'Mathías Suárez',
    '234377.0': 'Téji Savanier',
    '386611.0': 'Bastian Badu',
    '137174.0': 'Yun Il-Lok',
    '391287.0': 'Thibaut Vargas',
    '256226.0': 'Bilal Boutobba',
    '387159.0': 'Clément Vidal',
    '367414.0': 'Matis Carvalho'}},
  '313': {'name': 'Rennes',
   'players': {'29590.0': 'Romain Salin',
    '297540.0': 'Jérémy Gélin',
    '58761.0': "M'Baye Niang",
    '79562.0': 'Clément Grenier',
    '332144.0': 'James Léa Siliki',
    '289018.0': 'Hamari Traoré',
    '296232.0': 'Faitout Maouassa',
    '369109.0': 'Eduardo Camavinga',
    '296241.0': 'Flavien Tait',
    '34176.0': 'Damien Da Silva',
    '22115.0': 'Jérémy Morel',
    '260812.0': 'Jordan Siebatcheu',
    '372280.0': 'Sacha Boey',
    '345386.0': 'Gerzino Nyamsi',
    '300291.0': 'Romain Del Castillo',
    '129282.0': 'Benjamin Bourigeaud',
    '321390.0': 'Édouard Mendy',
    '129999.0': 'Adrien Hunou',
    '300447.0': 'Raphinha',
    '92792.0': 'Jonas Martin',
    '298545.0': 'Joris Gnagnon',
    '361815.0': 'Yann Gboho',
    '357533.0': 'Rafik Guitane',
    '328463.0': 'Souleyman Doumbia',
    '379615.0': 'Lucas da Cunha',
    '39935.0': 'Steven Nzonzi'}},
  '245': {'name': 'Nimes',
   'players': {'232582.0': 'Renaud Ripart',
    '234369.0': 'Anthony Briançon',
    '234405.0': 'Pablo Martinez',
    '143317.0': 'Zinedine Ferhat',
    '301047.0': 'Gaëtan Paquiez',
    '316029.0': 'Sofiane Alakouch',
    '296221.0': 'Antonin Bobichon',
    '234373.0': 'Théo Valls',
    '296340.0': 'Florian Miguel',
    '236563.0': 'Romain Philippoteaux',
    '288896.0': 'Paul Bernardoni',
    '318298.0': 'Haris Duljevic',
    '78041.0': 'Pierrick Valdivia',
    '372720.0': 'Théo Sainte-Luce',
    '381662.0': 'Sidy Sarr',
    '381663.0': 'Vlatko Stojanovski',
    '319464.0': 'Lamine Fomba',
    '35562.0': 'Lucas Deaux',
    '94932.0': 'Loïck Landre',
    '332814.0': 'Kévin Denkey',
    '335009.0': 'Sami Ben Amar',
    '330806.0': 'Lucas Dias',
    '363569.0': 'Lucas Buadés',
    '383564.0': 'Antoine Valério',
    '389063.0': 'Lucas Valls',
    '372890.0': 'Yassine Benrahou',
    '44609.0': 'Nolan Roux',
    '328436.0': 'Moussa Koné'}},
  '304': {'name': 'PSG',
   'players': {'255167.0': 'Thilo Kehrer',
    '248112.0': 'Abdou Diallo',
    '28550.0': 'Thiago Silva',
    '96449.0': 'Julian Draxler',
    '101949.0': 'Marquinhos',
    '106894.0': 'Juan Bernat',
    '300713.0': 'Kylian Mbappé',
    '91961.0': 'Marco Verratti',
    '94868.0': 'Pablo Sarabia',
    '24328.0': 'Edinson Cavani',
    '92516.0': 'Alphonse Areola',
    '23110.0': 'Ángel Di María',
    '104376.0': 'Thomas Meunier',
    '93700.0': 'Leandro Paredes',
    '361283.0': 'Colin Dagba',
    '80464.0': 'Idrissa Gueye',
    '29809.0': 'Eric Choupo-Moting',
    '373556.0': 'Arthur Zagré',
    '382491.0': 'Adil Aouchiche',
    '361433.0': 'Marcin Bulka',
    '92795.0': 'Layvin Kurzawa',
    '106028.0': 'Jesé',
    '50835.0': 'Neymar',
    '65901.0': 'Keylor Navas',
    '106964.0': 'Mauro Icardi',
    '71174.0': 'Ander Herrera',
    '247800.0': 'Presnel Kimpembe',
    '373555.0': 'Loïc Mbe Soh',
    '109338.0': 'Sergio Rico',
    '382492.0': 'Tanguy Nianzou',
    '352830.0': 'Mitchel Bakker'}},
  '314': {'name': 'Metz',
   'players': {'296372.0': 'Habib Diallo',
    '323211.0': 'Habib Maïga',
    '101911.0': 'Thomas Delaine',
    '323147.0': 'Mamadou Fofana',
    '34008.0': 'Alexandre Oukidja',
    '115837.0': 'Opa Nguette',
    '11908.0': 'Renaud Cohade',
    '298733.0': "Kévin N'Doram",
    '294496.0': 'Fabien Centonze',
    '294501.0': 'Farid Boulaya',
    '141592.0': 'Stoppila Sunzu',
    '342542.0': 'Ibrahima Niane',
    '259434.0': 'Marvin Gakpa',
    '285812.0': 'Victorien Angban',
    '67370.0': 'John Boye',
    '256844.0': 'Thierry Ambrose',
    '244297.0': 'Adama Traoré',
    '295590.0': 'Manuel Cabit',
    '286443.0': 'Matthieu Udol',
    '234388.0': 'Paul Delecroix',
    '389020.0': 'Georges Mikautadze',
    '90061.0': 'Vincent Pajot',
    '321150.0': 'Dylan Bronn',
    '391288.0': 'Papa Yade'}},
  '148': {'name': 'Strasbourg',
   'players': {'121711.0': 'Alexander Djiku',
    '105151.0': 'Kenny Lala',
    '362470.0': 'Youssouf Fofana',
    '92792.0': 'Jonas Martin',
    '90446.0': 'Lionel Carole',
    '113747.0': 'Adrien Thomasson',
    '137720.0': 'Dimitri Liénard',
    '34214.0': 'Lamine Koné',
    '84041.0': 'Stefan Mitrovic',
    '234364.0': 'Ludovic Ajorque',
    '78386.0': 'Matz Sels',
    '320242.0': 'Jean-Ricner Bellegarde',
    '342550.0': 'Nuno da Costa',
    '344143.0': 'Kévin Zohi',
    '203216.0': 'Abdallah Ndour',
    '372855.0': 'Mohamed Simakan',
    '306766.0': 'Ibrahima Sissoko',
    '329620.0': 'Lebo Mothiba',
    '90107.0': 'Benjamin Corgnet',
    '361902.0': 'Moataz Zemzemi',
    '382159.0': 'Adrien Lebeau',
    '107891.0': 'Sanjin Prcic',
    '321145.0': 'Anthony Caci',
    '84462.0': 'Abdul Waris',
    '34116.0': 'Jeremy Grimm'}},
  '37': {'name': 'Bayern',
   'players': {'37099.0': 'Thomas Müller',
    '129983.0': 'Niklas Süle',
    '74939.0': 'Thiago Alcântara',
    '134894.0': 'Corentin Tolisso',
    '259648.0': 'Benjamin Pavard',
    '283323.0': 'Joshua Kimmich',
    '119501.0': 'Serge Gnabry',
    '13754.0': 'Manuel Neuer',
    '39722.0': 'David Alaba',
    '29400.0': 'Robert Lewandowski',
    '125883.0': 'Kingsley Coman',
    '299450.0': 'Renato Sanches',
    '320040.0': 'Alphonso Davies',
    '139186.0': 'Lucas Hernández',
    '80767.0': 'Philippe Coutinho',
    '70524.0': 'Ivan Perisic',
    '14091.0': 'Javi Martínez',
    '344198.0': 'Michaël Cuisance',
    '23589.0': 'Jérôme Boateng',
    '115519.0': 'Leon Goretzka',
    '35506.0': 'Sven Ulreich',
    '379696.0': 'Sarpreet Singh',
    '383956.0': 'Joshua Zirkzee',
    '366855.0': 'Leon Dajaku',
    '317354.0': 'Álvaro Odriozola',
    '389378.0': 'Oliver Batista Meier',
    '346731.0': 'Kwasi Wriedt',
    '395401.0': 'Chris Richards',
    '395252.0': 'Jamal Musiala'}},

In [159]:
desc_team = utils.readJson('Descriptions/Descriptions/team_description_it_v2.json')
for line in desc_team['80']['prompt'].split('\n'):
    print(line)

Sei un football match analyst esperto.
        Ho bisogno che mi crei un report per una squadra di calcio basandoti sulle azioni compiute dai giocatori che la compongono.
        Utilizza queste informazioni per analizzare le caratteristiche tecniche e tattiche collettive della squadra, evidenziando lo stile di gioco, i punti di forza, le debolezze e le zone del campo maggiormente sfruttate.
        Per ogni giocatore è indicato il numero di presenze. Più è alto il numero delle presenze e maggiore sarà il suo contributo nello stile di gioco della squadra.
        Nel report non specificare nomi dei giocatori.
        La lista delle azioni per ciascun giocatore è fornita qui sotto:
        - Rafael Leão: presenze: 45, caratteristiche: ["tiro fuori bersaglio dall'interno dell'area attacco, centro sinistra", "tiro fuori bersaglio dall'interno dell'area attacco, centro destra", "tiro dall'area di rigore attacco, centro sinistra", "tiro dall'area piccola attacco, centro sinistra", "tiro dall'area di rigore attacco, centro destra"]
- Theo Hernández: presenze: 44, caratteristiche: ['tiro alto vicino alla traversa centrocampo, fascia sinistra', 'tiro alto vicino alla traversa centrocampo, fascia destra', "preciso da calcio d'angolo centrocampo, fascia sinistra", "assist da calcio d'angolo centrocampo, fascia destra", "assist da calcio d'angolo centrocampo, fascia sinistra"]
- Mike Maignan: presenze: 41, caratteristiche: ['preciso in avanti difesa, centrale', 'preciso da punizione difesa, centrale', 'corto preciso difesa, centrale', 'assist di altro tipo difesa, centrale', 'tiro alto fuori bersaglio difesa, centrale']
- Malick Thiaw: presenze: 30, caratteristiche: ['passaggio chiave da punizione trequarti difensiva, centro destra', 'passaggio chiave corto trequarti difensiva, centro destra', 'passaggio chiave trequarti difensiva, centro destra', 'passaggio chiave filtrante trequarti difensiva, centro destra', 'passaggio chiave lungo trequarti difensiva, centro destra']
- Fikayo Tomori: presenze: 35, caratteristiche: ['preciso da punizione trequarti difensiva, centro destra', 'passaggio chiave filtrante trequarti difensiva, centro sinistra', 'passaggio chiave trequarti difensiva, centro destra', 'passaggio chiave corto trequarti difensiva, centro sinistra', 'passaggio chiave filtrante trequarti difensiva, centro destra']
- Rade Krunic: presenze: 14, caratteristiche: ['passaggio chiave filtrante trequarti difensiva, centro destra', 'passaggio chiave da punizione trequarti difensiva, centro destra', 'passaggio chiave lungo trequarti difensiva, centro destra', 'assist su cross trequarti difensiva, centro destra', 'passaggio chiave da rimessa laterale trequarti difensiva, centro destra']
- Tijjani Reijnders: presenze: 48, caratteristiche: ['autogoal trequarti offensiva, centro destra', "centro dell'area piccola trequarti offensiva, centro destra", 'intercetta in area di rigore trequarti offensiva, centro destra', "centro dell'area piccola trequarti offensiva, centro sinistra", 'preciso trequarti offensiva, centro destra']
- Olivier Giroud: presenze: 46, caratteristiche: ["tiro fuori bersaglio dall'interno dell'area centrocampo, centrale", "tiro dall'area piccola centrocampo, centrale", "tiro dall'area di rigore centrocampo, centrale", 'azione eseguita con una parte del corpo diversa centrocampo, centrale', 'azione di contropiede centrocampo, centrale']
- Davide Calabria: presenze: 39, caratteristiche: ['tiro alto vicino alla traversa trequarti difensiva, centro destra', 'spazzata efficace trequarti difensiva, centro destra', 'assist da rimessa laterale trequarti difensiva, centro destra', 'tiro di poco fuori alto a destra trequarti difensiva, centro destra', 'tiro di destro trequarti difensiva, centro destra']
- Ruben Loftus-Cheek: presenze: 39, caratteristiche: ['scarico semplice al compagno attacco, centro sinistra', 'scarico semplice al compagno attacco, centro destra', 'passaggio chiave da punizione attacco, centro destra', 'passaggio chiave corto attacco, centro destra', 'Sanzione attacco, centro sinistra']
- Christian Pulisic: presenze: 48, caratteristiche: ["parata effettuata nell'area piccola attacco, centro sinistra", 'intercettazione riuscita attacco, centro sinistra', "blocco nell'area piccola attacco, centro sinistra", "blocco nell'area piccola attacco, centro destra", 'rigore guadagnato attacco, centro destra']
- Noah Okafor: presenze: 36, caratteristiche: ['Esce giocatore attacco, centro destra', 'Esce giocatore attacco, centro sinistra', 'Esce giocatore attacco, centrale', 'Passaggio a giocatore in fuorigioco attacco, centrale', 'Entra giocatore attacco, centro destra']
- Tommaso Pobega: presenze: 15, caratteristiche: ['gol in azione di gioco trequarti offensiva, centro destra', 'Presa del pallone in aria o in mischia trequarti offensiva, centro destra', 'gol in azione di gioco trequarti offensiva, centro sinistra', 'assist intenzionale per un gol trequarti offensiva, centro destra', 'Passaggio a giocatore in fuorigioco trequarti offensiva, centro destra']
- Pierre Kalulu: presenze: 11, caratteristiche: ['Esce giocatore trequarti difensiva, centro destra', 'Entra giocatore trequarti difensiva, centro destra', 'Passaggio a giocatore in fuorigioco trequarti difensiva, centro destra', 'Esce giocatore trequarti difensiva, centro sinistra', 'Entra giocatore trequarti difensiva, centro sinistra']
- Samuel Chukwueze: presenze: 32, caratteristiche: ['perde il controllo del pallone correndo attacco, centro destra', 'perde il controllo del pallone correndo attacco, centro sinistra', 'perde il controllo del pallone attacco, centro destra', 'perde il controllo del pallone attacco, centro sinistra', 'portiere che cattura con successo un pallone alto attacco, centro destra']
- Simon Kjær: presenze: 24, caratteristiche: ['passaggio chiave corto trequarti difensiva, centro destra', 'passaggio chiave filtrante trequarti difensiva, centro destra', 'passaggio chiave lungo trequarti difensiva, centro destra', 'passaggio chiave trequarti difensiva, centro destra', 'passaggio chiave da punizione trequarti difensiva, centro destra']
- Yunus Musah: presenze: 39, caratteristiche: ['passaggio chiave lungo difesa, centro destra', 'crea una grande occasione difesa, centro destra', 'passaggio chiave lungo difesa, centro sinistra', 'passaggio chiave filtrante difesa, centro destra', 'passaggio chiave da punizione difesa, centro destra']
- Alessandro Florenzi: presenze: 39, caratteristiche: ['tiro alto vicino alla traversa trequarti difensiva, centro destra', 'tiro di poco fuori alto a destra trequarti difensiva, centro destra', 'passaggio chiave da rimessa laterale trequarti difensiva, centro destra', 'errore che porta a tiro trequarti difensiva, centro destra', 'tiro di poco fuori alto a sinistra trequarti difensiva, centro destra']
- Luka Jovic: presenze: 28, caratteristiche: ['Presa del pallone in aria o in mischia difesa, centrale', 'rigore segnato ai calci di rigore centrocampo, centrale', 'Presa del pallone in aria o in mischia centrocampo, centrale', 'duello aereo vinto centrocampo, centrale', 'rigore concesso ai calci di rigore centrocampo, centrale']
- Marco Sportiello: presenze: 9, caratteristiche: ['assist intenzionale per un gol difesa, centrale', "gol dall'area piccola difesa, centrale", 'corto preciso difesa, centrale', 'assist di altro tipo difesa, centrale', 'tiro alto fuori bersaglio difesa, centrale']
- Davide Bartesaghi: presenze: 7, caratteristiche: ['Esce giocatore difesa, fascia destra', 'Passaggio a giocatore in fuorigioco difesa, fascia destra', 'Passaggio a giocatore in fuorigioco difesa, fascia sinistra', 'Esce giocatore difesa, fascia sinistra', 'Presa del pallone in aria o in mischia difesa, fascia destra']
- Yacine Adli: presenze: 32, caratteristiche: ['passaggio chiave da punizione trequarti difensiva, centro destra', 'passaggio chiave filtrante trequarti difensiva, centro destra', 'passaggio chiave da punizione trequarti difensiva, centro sinistra', 'passaggio chiave da rimessa laterale trequarti difensiva, centro destra', 'passaggio chiave lungo trequarti difensiva, centro destra']
- Luka Romero: presenze: 17, caratteristiche: ['Esce giocatore trequarti offensiva, centro destra', 'Esce giocatore trequarti offensiva, centro sinistra', 'Esce giocatore trequarti offensiva, centrale', 'Passaggio a giocatore in fuorigioco trequarti offensiva, centro destra', 'Entra giocatore trequarti offensiva, centro destra']
- Antonio Mirante: presenze: 2, caratteristiche: ['corto preciso difesa, centro destra', 'preciso in avanti difesa, centro destra', 'corto preciso difesa, centro sinistra', 'preciso in avanti difesa, centro sinistra', 'assist di altro tipo difesa, centro destra']
- Marco Pellegrino: presenze: 11, caratteristiche: ['crea una grande occasione difesa, centro destra', 'creazione di una grande occasione da gol difesa, fascia destra', 'segna una grande occasione difesa, centro destra', 'assist intenzionale per un gol difesa, fascia destra', 'creazione di una grande occasione da gol difesa, fascia sinistra']
- Francesco Camarda: presenze: 2, caratteristiche: ['duello aereo perso difesa, centro destra', 'Presa del pallone in aria o in mischia difesa, centro destra', 'Presa del pallone in aria o in mischia difesa, centro sinistra', 'duello aereo perso difesa, centro sinistra', 'rigore concesso ai calci di rigore difesa, centro destra']
- Ismaël Bennacer: presenze: 25, caratteristiche: ['passaggio chiave da punizione centrocampo, centrale', 'parata su situazione pericolosa centrocampo, centrale', 'passaggio chiave centrocampo, centrale', 'passaggio chiave corto centrocampo, centrale', 'perde il controllo del pallone correndo centrocampo, centrale']
- Jan-Carlo Simic: presenze: 4, caratteristiche: ['Esce giocatore trequarti difensiva, centro destra', 'Esce giocatore trequarti difensiva, centro sinistra', 'Entra giocatore trequarti difensiva, centro destra', 'Passaggio a giocatore in fuorigioco trequarti difensiva, centro destra', 'Entra giocatore trequarti difensiva, centro sinistra']
- Chaka Traorè: presenze: 3, caratteristiche: ['uno contro uno trequarti offensiva, fascia destra', 'uno contro uno trequarti offensiva, fascia sinistra', 'Goal trequarti offensiva, fascia destra', 'Goal trequarti offensiva, fascia sinistra', 'assist trequarti offensiva, fascia destra']
- Kevin Zeroli: presenze: 3, caratteristiche: ['Esce giocatore difesa, centrale', 'Passaggio a giocatore in fuorigioco difesa, centrale', 'creazione di una grande occasione da gol difesa, centro destra', 'creazione di una grande occasione da gol difesa, centrale', "azione derivante da calcio d'angolo difesa, centrale"]
- Álex Jiménez: presenze: 3, caratteristiche: ['assist intenzionale per un gol difesa, fascia sinistra', 'assist intenzionale per un gol difesa, fascia destra', 'creazione di una grande occasione da gol difesa, fascia sinistra', 'creazione di una grande occasione da gol difesa, fascia destra', 'gol in azione di gioco difesa, fascia sinistra']
- Matteo Gabbia: presenze: 33, caratteristiche: ['parata in sicurezza trequarti difensiva, centro destra', 'Blocco rapido a terra difesa, centro destra', 'parata in sicurezza trequarti difensiva, centro sinistra', 'passaggio chiave filtrante trequarti difensiva, centro destra', 'passaggio chiave da rimessa laterale trequarti difensiva, centro destra']
- Filippo Terracciano: presenze: 23, caratteristiche: ['Presa del pallone in aria o in mischia difesa, fascia destra', 'portiere che cattura con successo un pallone alto difesa, fascia destra', 'rigore segnato ai calci di rigore difesa, fascia destra', 'tiro in azione di gioco difesa, fascia destra', 'tiro in azione di gioco difesa, fascia sinistra']
- Mattia Caldara: presenze: 1, caratteristiche: ['Esce giocatore difesa, centro sinistra', 'Esce giocatore difesa, centro destra', 'Esce giocatore difesa, centrale', 'Passaggio a giocatore in fuorigioco difesa, centro destra', 'Passaggio a giocatore in fuorigioco difesa, centro sinistra']
- Lapo Nava: presenze: 1, caratteristiche: ["tiro fuori bersaglio dall'interno dell'area difesa, centro destra", "tiro fuori bersaglio dall'interno dell'area difesa, centro sinistra", "tiro dall'area di rigore difesa, centro destra", "tiro dall'area di rigore difesa, centro sinistra", "zona profonda a sinistra dell'area di rigore difesa, centrale"]

    ###Formato output
            *Caratteristiche*:
            Evidenzia le caratteristiche tecnico tattiche che meglio rappresentano la squadra
            *Punti di forza*:
            Evidenzia i punti di forza principali della squadra emersi dal suo stile di gioco.
            *Debolezze*:
            Indica le aree in cui la squadra deve migliorare.
            *Zone del campo predilette*:
            Identifica le zone del campo in cui la squadra è più attiva o performa meglio.
    ###Note per l'analisi
            - Usa un linguaggio conciso e professionale.
            - Il report deve essere realistico e utile per scopi di osservazione calcistica.
            - Non generare codice o strutture di classe. Concentrati solo sull'analisi calcistica.
            - L'output deve essere in testo semplice, chiaramente formattato secondo la struttura sopra indicata.
            - Non scrivere i nomi dei giocatori.
            - Importante, genera il report considerando solo le informazioni indicate in input.

        Genera solo il contenuto del rapporto. Non includere spiegazioni, istruzioni, o altre informazioni oltre a quelle richieste.
        ###Report generato:

In [160]:
for line in desc_team['80']['description'].split('\n'):
    print(line)

     Caratteristiche:
         Squadra molto dinamica nel movimento palla. Giocatori veloci ed abili nei passaggi brevi.
         Stilisticamente, si adatta bene all'estetica moderna del calcio europeo.

     Debolezze:
         Molto dipendenti dalla capacità individuale dei singoli giocatori piuttosto che dalle qualità costruttive come unità.

     Zone del Campo Predilette:
         Centrocampo (Centrale): Questa zona del campo viene utilizzata principalmente dagli assistentti per prepararsi alle loro partite future. Si concentriamo sulla sua posizione strategica perché permetterebbe agli assistenti di fare più flessibilità nella loro preparazione prima di andare in gara.

In [161]:
for line in desc_team['75']['description'].split('\n'):
    print(line)

     #### Caratteristiche:

La **squadra** ha dimostrato di possedere uno **stile di gioco** basato sulla **premura**, con **una forte tendenza ad eseguire passaggi rapidamente nel terreno di gioco,** soprattutto nelle fasce esterne e nella zona di mezzo. Questo approccio li rende particolarmente dinamici ed efficaci nei momenti cruciali dello sviluppo di situazioni di gioco.

Il loro repertorio comprende anche alcune strategie offensive avanzate come **"Crossing"**, dove cercano di inserire i propri compagni attraverso precise palle alte e incisivi calci lunghi verso gli angoli, ma questo aspetto si rivela meno dominante rispetto all'impostazione generalista di base.

Nel complesso, questa combinazione di aggressività e velocità offre alle squadre un vantaggio competitivo significativo, specialmente quando vengono utilizzate contro avversari con linee mediane più indietregiate.


#### Punti di Forza

I punti di forza principali della **squadra** sono principalmente legati ai suoi elementi centrali, ovvero i **difensori** e i **mediocentri**. In particolare, questi componenti sembrano avere un ruolo cruciale sia nel contrasto diretto degli avversari, sia nell'aiutare la costruzione dell'offensive finale.

Inoltre, il modo in cui **questi giocatori lavorano insieme** permette alla squadra di ottenere risultati migliori. Ad esempio, alcuni mediocentri mostrano capacità impressionanti nel recuperare pallone e poi servirli agli altri membri della linea offensiva, mentre altri hanno abilità straordinarie negli ultimi metri prima di entrare in porta.

Questo equilibrio tra diversificazione e complementarietà consente alla **squadra** di mantenere sempre alta la pressione sui propri rivali, impedendo loro di raccogliersi troppo facilmente dopo aver subito perdite.

Infine, va notato quanto **determinanti** siano stati i difensori nella gestione di molte partite decisive. Grazie alla loro combattività e

In [162]:
for line in desc_team['52']['description'].split('\n'):
    print(line)

    	##Caratteristiche

    		La squadra ha dimostrato una forte abilità nel mantenimento della palla all’interno dello stesso terreno di gioco, grazie alla combinazione tra passaggi veloci e accurati da parte degli attaccanti, insieme alle loro buone capacità fisiche per recuperarla rapidamente nei momenti cruciali. Inoltre, la squadra mostra uno stile aggressivo ed energico quando si tratta di entrare nelle aree d’attacco avversarie, utilizzando principalmente calci lunghi e diagonali verso gli estremisti o i secondini centrali. Questo stile rende difficile ai difensori opposti fermarlo, poiché hanno difficoltà ad anticipare questi movimenti rapidi e dinamici. Infine, la squadra presenta anche una certa varietà negli schemi di gioco, scegliendo frequentemente diverse soluzioni strategiche durante partite importanti come quella contro Real Madrid (0-3), dove sono stati in grado di controllare completamente il risultato fino al termine del tempo regolare senza concedere nessuna possibilità agli avversari di trovare un punto debole nella propria linea difensiva.

    	##Punti di Forza:

    		L’inizio molto positivo della stagione ha permesso alla squadra di stabilirsi subito come favoriti per vincere il campionato nazionale, soprattutto dopo aver vinto tutti i primi quattro incontri casalinghi consecutivamente. Grazie a questo ottimo avvio, la squadra ha potuto concentrarsi maggiormente sui suoi obiettivi principali quali la qualificazione europea e la conquista del titolo domestico.

    	Infatti, già dalla prima giornata di ritorno, la squadra è stata capace di ribaltare nettamente due gare consecutive contro Juventus Torino (4-1) e Inter Milano (3-2). Ciò ha confermato ulteriormente la sua posizione dominatrice all’interno del girone A del massimo torneo italiano. Conclusasi poi questa fase importante del calendario sportivo, la squadra ha continuato a mostrare costanza sia nelle sue prestazioni individuali che nella coesione di gruppo, ottenendo

In [117]:
import utils
#records = utils.readJson('Descriptions/prova_stats_v2.json')
i=0
for line in prompts["Rafael Leão"]['prompt']['Defensive'].split('\n'):
    if i >= 20:
        print(line)

    i+=1

            -Generate a natural, fluent description:
                Highlight key strengths that define the player's ability.
                Mention secondary strengths if relevant.
                Point areas for improvement, keeping a constructive tone.


        ## Input Format:
            - **Position:** Preferred positions
            - **Statistics:** Per-match data with **values** and **percentiles** (0-100). A high percentile indicates **strong performance** relative to players in the same position.

        ## Output Guidelines:
            - **Professional & concise** language suitable for scouting.
            - **Plain text only** (no bullet points, code, or structured output).
            - **Do not include raw statistics** (focus on interpretation).
            - **No predictions** about future performance.
            - **Only use provided data**, without speculation.
            - **The description should be role-specific**, considering the player's position.

        ## Example Output:
            A well-rounded attacking midfielder with exceptional ability in progressing the ball and creating goal-scoring opportunities. He excels in shot-creating actions, with a strong ability to beat defenders through take-ons. His capacity to contribute directly to goals is elite. While highly effective in offensive play, his involvement in defensive phases and dead-ball situations is less prominent, indicating areas for potential development.

        ### Input Data:
            - **Position**: Forwarder, Midfielder, Attacking midfielder
            - **Statistics**: {'Tackles': {'description': 'Number of players tackled', 'value': '0.57', 'percentile': '5'}, 'Tackles Won': {'description': "Tackles in which the tackler's team won possession of the ball", 'value': '0.36', 'percentile': '9'}, 'Tackles (Def 3rd)': {'description': 'Tackles in defensive 1/3', 'value': '0.11', 'percentile': '6'}, 'Tackles (Mid 3rd)': {'description': 'Tackles in middle 1/3', 'value': '0.29', 'percentile': '19'}, 'Tackles (Att 3rd)': {'description': 'Tackles in attacking 1/3', 'value': '0.18', 'percentile': '32'}, 'Dribblers Tackled': {'description': 'Number of dribblers tackled', 'value': '0.29', 'percentile': '12'}, 'Dribbles Challenged': {'description': 'Number of unsuccessful challenges plus number of dribblers tackled', 'value': '0.47', 'percentile': '1'}, '% of Dribblers Tackled': {'description': '<strong>Percentage of dribblers tackled</strong><br>Dribblers tackled divided by number of attempts to challenge an opposing dribbler<br>Minimum .625 dribblers challenged per squad game to qualify as a leader', 'value': '61.5%', 'percentile': '91'}, 'Challenges Lost': {'description': 'Number of unsucessful attempts to challenge a dribbling player', 'value': '0.18', 'percentile': '99'}, 'Blocks': {'description': 'Number of times blocking the ball by standing in its path', 'value': '0.54', 'percentile': '18'}, 'Shots Blocked': {'description': 'Number of times blocking a shot by standing in its path', 'value': '0.04', 'percentile': '32'}, 'Passes Blocked': {'description': 'Number of times blocking a pass by standing in its path', 'value': '0.50', 'percentile': '19'}, 'Interceptions': {'description': 'Interceptions', 'value': '0.32', 'percentile': '35'}, 'Tkl+Int': {'description': 'Number of players tackled plus number of interceptions', 'value': '0.90', 'percentile': '9'}, 'Clearances': {'description': 'Clearances', 'value': '0.68', 'percentile': '61'}, 'Errors': {'description': "Mistakes leading to an opponent's shot", 'value': '0.00', 'percentile': '61'}, 'Yellow Cards': {'description': 'Yellow Cards', 'value': '0.18', 'percentile': '49'}, 'Red Cards': {'description': 'Red Cards', 'value': '0.00', 'percentile': '55'}, 'Second Yellow Card': {'description': 'Second Yellow Card', 'value': '0.00', 'percentile': '53'}, 'Fouls Committed': {'description': 'Fouls Committed', 'value': '0.97', 'percentile': '60'}, 'Fouls Drawn': {'description': 'Fouls Drawn', 'value': '1.86', 'percentile': '61'}, 'Offsides': {'description': 'Offsides', 'value': '0.61', 'percentile': '8'}, 'Crosses': {'description': 'Crosses', 'value': '3.87', 'percentile': '73'}, 'Penalty Kicks Won': {'description': 'Penalty Kicks Won', 'value': '0.07', 'percentile': '96'}, 'Penalty Kicks Conceded': {'description': 'Penalty Kicks Conceded', 'value': '0.04', 'percentile': '5'}, 'Own Goals': {'description': 'Own Goals', 'value': '0.00', 'percentile': '51'}, 'Ball Recoveries': {'description': 'Number of loose balls recovered', 'value': '2.79', 'percentile': '5'}, 'Aerials Won': {'description': 'Aerials Won', 'value': '0.86', 'percentile': '64'}, 'Aerials Lost': {'description': 'Aerials Lost', 'value': '0.61', 'percentile': '84'}, '% of Aerials Won': {'description': 'Percentage of aerials won<br>Minimum .97 aerial duels per squad game to qualify as a leader', 'value': '58.5%', 'percentile': '95'}}

        ###Generated Report:

In [99]:
desc = utils.readJson('Descriptions/Descriptions/prova_stats_v2.json')
desc_p = desc["Rafael Leão"]['description']
for t in desc_p.keys():
    print(t)
    i=0
    for line in desc_p[t].split('\n'):
        if i >= 0 and len(line.strip()) > 0:
            print(line)

        i+=1

Shooting
                This player has demonstrated strong shooting ability across multiple metrics. They consistently score goals at an impressive rate, averaging 0.32 goals per match which places them in the top 80th percentile among forwards, midfielders, and attacking midfielders. Their overall contribution to scoring opportunities is evident through 2.51 total shots per game, ranking them in the 77th percentile. However, while they take many shots, only 34% find their way on target—a mark below the expected threshold—placing them at the 58th percentile.
                Despite this, their efficiency remains notable; they convert one out of every seven shots into a goal (0.13 G/S), putting them in the 75th percentile. Moreover, when shots are on target, they have a high conversion rate of 0.38 goals per shot on target, landing them in the 73rd percentile. Their average shot distance of 17.10 yards suggests a preference for taking well-positioned attempts rather than speculative efforts from farther away.
                While their non-penalty expected goals (npxG) of 0.36 highlight their consistent finishing quality, placing them in the 92nd percentile, areas requiring attention include improving their accuracy (shots on target percentage could use improvement) and perhaps reducing reliance solely on long-range efforts. Additionally, their lack of contributions via free kicks and penalties, both sitting at zero, presents another area for development. Overall, this player offers significant offensive potential but would benefit from refining specific aspects of their shooting technique and positioning.'</think>
</think>
This player exhibits solid shooting skills, particularly excelling in converting chances into goals. With an average of 0.32 goals per match, they rank highly within their positional group, specifically in the 80th percentile. Their ability to create scoring opportunities is reflected in 2.51 total shots per game, placing them in the 77th percentile. Notably, despite these numbers, their shot accuracy leaves room for growth, as only 34% of their shots are on target—an area where they fall short compared to peers, standing at the 58th percentile.
Efficiency remains a strength, however, as they achieve a 0.13 goals-per-shot ratio, situating them in the 75th percentile. When shots are on target, their conversion rate of 0.38
Offensive
                This forward has demonstrated exceptional ability in creating chances through various methods, consistently ranking among top performers across all SCA metrics. Their success rate in successful take-ons is impressive, particularly in high-pressure areas like the attacking penalty zone, where they average over six touches per game. They show strong progression in carrying the ball, especially notable in both total and progressive distances covered, often breaking lines and entering dangerous zones frequently.
                However, despite these strengths, some aspects require attention. Their pass completion percentage is relatively low compared to peers, suggesting room for improvement in delivering accurate and decisive passes under pressure. Additionally, while their assist numbers are solid, enhancing their final product quality could elevate their contribution to the team's attack further.
</think>
This forward/midfielder/attacking midfielder excels in generating scoring opportunities, showcasing elite skills in creating shots and goals through diverse techniques. With a remarkable 92nd percentile in Shot-Creating Actions and a stellar 99th percentile in Goal-Creating Actions, the player consistently ranks among the best in their positional group at turning possessions into threats. Their ability to draw fouls effectively (85th percentile) adds another layer to their offensive prowess, often disrupting defenses and creating additional openings.
Technically, the player demonstrates precision in close combat, highlighted by a 95th percentile in Successful Take-Ons and a commendable 50% take-on success rate (88th percentile). Their capacity to maintain composure under pressure is evident, as they rarely lose possession due to tackles (only 1.47 dispossessions per game), placing them in the 40th percentile—a mark of reliability in high-stakes situations.
The player’s influence extends beyond direct creation; they contribute significantly to build-up play with a robust 94th percentile in Progressive Carrying Distance and a standout 98th percentile in Progressive Carries. These stats underscore their role in advancing the ball efficiently into dangerous areas, frequently penetrating the opposition’s final third and even their penalty box—key attributes for sustained attacking威胁。
Despite these strengths, the player’s passing accuracy leaves room for growth, sitting at a modest 73.6% completion rate (39th percentile). Enhancing this aspect would allow for greater consistency in linking play and maximizing their creative impact.
Defensive
                **Player:** [Name]
                **Position(s):** Forwarder, Midfielder, Attacking Midfielder
                **Defensive Overview:**
                This player demonstrates solid defensive contributions across multiple thirds but has room for improvement in certain areas. Their ability to win tackles stands out, particularly in the middle third, showcasing strong positioning and timing. However, they struggle slightly when tackling in the attacking third and may need to work on reducing errors here. They also have a high success rate in challenging dribblers, indicating effective pressure application, though occasional lost challenges can disrupt their defensive consistency.
                Additionally, the player contributes well through aerial battles, averaging over 0.86 aerial wins per game at a 64th percentile, reflecting decent strength and jumping ability. Ball recoveries are another area of strength, demonstrating quick reactions and proactive involvement in regaining possession. Despite these positives, there’s room for growth in improving tackle efficiency, especially in higher-pressure zones like the attacking third, and minimizing fouling incidents to avoid disrupting attacks unnecessarily.
Okay, so I'm trying to figure out how to create a defensive overview for this player based on the stats given. Let me start by looking at all the defensive metrics provided. First off, the player plays as a forwarder, midfielder, or attacking midfielder, so their role likely involves both contributing offensively and defensively from those positions.
Looking at the numbers, let's break them down one by one. Starting with Tackles overall, he averages 0.57 per game, placing him at the 5th percentile. That seems low; maybe he doesn't get many opportunities to tackle? But then again, his Tackles Won percentage is much better—only 0.36 per game but at the 9th percentile. Wait, no—that might mean more than half his tackles are successful since 9%iles aren't great... Hmm, actually, wait—the percentiles compare within the same position group, right?
Wait, hold on. If the player is in the 9th percentile for Tackles Won, does that mean only 9% of players in similar positions perform worse? Or better? Because if it's 9%, that would imply he's among the top 9%. No, usually, higher percentile means better performance. So being in the 9th percentile for Tackles Won suggests he's near the bottom—it's confusing because sometimes lower values could mean

In [100]:
def getRoles(role):
    rr=[]
    if '(' in role:
        roles_split = role.split('(')
    else:
        roles_split = [role]

    for r in roles_split:
        if '-' in r:
            r_split = r.split('-')
            rr.append(r_split[0])
            rl = r_split[1]
            if rl[-1] == ')':
                rl = rl[:-1]
            rr.append(rl)

        elif ',' in r:
            rr.append(r.split(',')[0])
        elif ')' in r:
            rr.append(r[:-1])
        else:
            rr.append(r.strip())


    return rr

In [101]:
from utils import readJson, writeJson

In [109]:
prompts = {}
records = readJson('Dataset/Fbref/prova_records_perc_v2.json')
position_dict = readJson('Dataset/Fbref/position_mapping.json')
stats_dict = {'Shooting': ['Shooting'],'Offensive':[ 'Goal and Shot Creation', 'Possession','Passing', 'Pass Types'], 'Defensive':['Defense', 'Miscellaneous Stats']}
for p in records[:1]:
    player_name = p['player']
    prompts[player_name] = {'prompt':{}}
    roles = getRoles(p['position'])
    roles_verb = [position_dict[x.strip()] for x in roles]
    roles_str = ', '.join(roles_verb)
    for k, tab  in stats_dict.items():
        stat = {}
        for t in tab:
            stat = stat | p['stats'][t]
        prompt = f""""You are a professional soccer scout with expertise in analyzing players' technical and tactical characteristics.
        ## Task:  
        Generate a concise description (200-300 tokens) of a player's {k} performance based on the provided per-match statistics. 
        The analysis should:    
            - Highlight the player's **key strengths** (high percentiles).
            - Identify potential **areas for improvement** (low percentiles).
            - Be **role-specific**, considering the player's position.
        
        ## Reasoning Process:
            - For each statistic, analyze its percentile ranking, classifying performance using these thresholds:
                Excellent (≥90th percentile) -> Major strength
                Very Good (75-89th percentile) -> Significant asset
                Good (50-74th percentile) -> Competent ability
                Average (30-49th percentile) -> Room for improvement
                Weak (<30th percentile) -> Notable weakness

            - Interpret the player's style of play:
                Identify how the player's strengths shape their contributions.
                Explain how weaknesses may limit their effectiveness.
            
            -Generate a natural, fluent description:
                Highlight key strengths that define the player's ability.
                Mention secondary strengths if relevant.
                Point areas for improvement, keeping a constructive tone.
            

        ## Input Format:
            - **Position:** Preferred positions 
            - **Statistics:** Per-match data with **values** and **percentiles** (0-100). A high percentile indicates **strong performance** relative to players in the same position.
        
        ## Output Guidelines:
            - **Professional & concise** language suitable for scouting.
            - **Plain text only** (no bullet points, code, or structured output).
            - **Do not include raw statistics** (focus on interpretation).
            - **No predictions** about future performance.
            - **Only use provided data**, without speculation.
            - **The description should be role-specific**, considering the player's position.
        
        ## Example Output:
            A well-rounded attacking midfielder with exceptional ability in progressing the ball and creating goal-scoring opportunities. He excels in shot-creating actions, with a strong ability to beat defenders through take-ons. His capacity to contribute directly to goals is elite. While highly effective in offensive play, his involvement in defensive phases and dead-ball situations is less prominent, indicating areas for potential development.

        ### Input Data:
            - **Position**: {roles_str}
            - **Statistics**: {stat}
            
        ###Generated Report:"""


        prompts[player_name]['prompt'][k] = prompt

#writeJson(prompts, 'Descriptions/prova_stats_v2.json')

In [104]:
prompts['Rafael Leão']['prompt']

{'Shooting': '"You are a professional soccer scout with expertise in analyzing players\' technical and tactical characteristics.  \n        Generate a concise description (200-300 tokens) of a player\'s Shooting performance based on the provided per-match statistics. \n        The analysis should:    \n            - Highlight the player\'s **key strengths** (high percentiles).\n            - Identify potential **areas for improvement** (low percentiles).\n            - Be **role-specific**, considering the player\'s position.\n\n        ## Input Format:\n            - **Position:** Preferred positions \n            - **Statistics:** Per-match data with **values** and **percentiles** (0-100). A high percentile indicates **strong performance** relative to players in the same position.\n        \n        ## Output Guidelines:\n            - **Professional & concise** language suitable for scouting.\n            - **Plain text only** (no bullet points, code, or structured output).\n            - **Do not include raw statistics** (focus on interpretation).\n            - **No predictions** about future performance.\n            - **Only use provided data**, without speculation.\n            - **The description should be role-specific**, considering the player\'s position.\n        \n        ## Example Output:\n            A well-rounded attacking midfielder with exceptional ability in progressing the ball and creating goal-scoring opportunities. He excels in shot-creating actions, with a strong ability to beat defenders through take-ons. His capacity to contribute directly to goals is elite. While highly effective in offensive play, his involvement in defensive phases and dead-ball situations is less prominent, indicating areas for potential development.\n\n        ### Input Data:\n            - **Position**: Forwarder, Midfielder, Attacking midfielder\n            - **Statistics**: {\'Goals\': {\'description\': \'Goals scored or allowed\', \'value\': \'0.32\', \'percentile\': \'80\'}, \'Shots Total\': {\'description\': \'Shots Total<br>Does not include penalty kicks\', \'value\': \'2.51\', \'percentile\': \'77\'}, \'Shots on Target\': {\'description\': \'Shots on Target<br>Note: Shots on target do not include penalty kicks\', \'value\': \'0.86\', \'percentile\': \'75\'}, \'Shots on Target %\': {\'description\': \'Percentage of shots that are on target<br>Minimum .395 shots per squad game to qualify as a leader<br>Note: Shots on target do not include penalty kicks\', \'value\': \'34.3%\', \'percentile\': \'58\'}, \'Goals/Shot\': {\'description\': \'Goals per shot<br>Minimum .395 shots per squad game to qualify as a leader\', \'value\': \'0.13\', \'percentile\': \'75\'}, \'Goals/Shot on Target\': {\'description\': \'Goals per shot on target<br>Minimum .111 shots on target per squad game to qualify as a leader<br>Note: Shots on target do not include penalty kicks\', \'value\': \'0.38\', \'percentile\': \'73\'}, \'Average Shot Distance\': {\'description\': \'Average distance, in yards, from goal of all shots taken<br>Minimum .395 shots per squad game to qualify as a leader<br>Does not include penalty kicks\', \'value\': \'17.10\', \'percentile\': \'71\'}, \'Shots from Free Kicks\': {\'description\': \'Shots from Free Kicks\', \'value\': \'0.00\', \'percentile\': \'25\'}, \'Penalty Kicks Made\': {\'description\': \'Penalty Kicks Made\', \'value\': \'0.00\', \'percentile\': \'38\'}, \'Penalty Kicks Attempted\': {\'description\': \'Penalty Kicks Attempted\', \'value\': \'0.00\', \'percentile\': \'36\'}, \'xG: Expected Goals\': {\'description\': \'Expected Goals<br>xG totals include penalty kicks, but do not include penalty shootouts (unless otherwise noted).<br>Provided by Opta.<br>An underline indicates there is a match that is missing data, but will be updated when available.\', \'value\': \'0.36\', \'percentile\': \'88\'}, \'npxG: Non-Penalty xG\': {\'description\': \'<strong>Non-Penalty Expected Goals</strong><br>Provided by Opta.<br>An underline indicates there is a match that is missing data, but will be updated when available.\', \'value\': \'0.36\', \'percentile\': \'92\'}, \'npxG/Shot\': {\'description\': \'Non-Penalty Expected Goals per shot<br>Provided by Opta.<br>An underline indicates there is a match that is missing data, but will be updated when available.<br>Minimum .395 shots per squad game to qualify as a leader\', \'value\': \'0.14\', \'percentile\': \'94\'}, \'Goals - xG\': {\'description\': \'<strong>Goals minus Expected Goals</strong><br>xG totals include penalty kicks, but do not include penalty shootouts (unless otherwise noted).<br>Provided by Opta.<br>An underline indicates there is a match that is missing data, but will be updated when available.\', \'value\': \'-0.04\', \'percentile\': \'27\'}, \'Non-Penalty Goals - npxG\': {\'description\': \'<strong>Non-Penalty Goals minus Non-Penalty Expected Goals</strong><br>xG totals include penalty kicks, but do not include penalty shootouts (unless otherwise noted).<br>Provided by Opta.<br>An underline indicates there is a match that is missing data, but will be updated when available.\', \'value\': \'-0.04\', \'percentile\': \'26\'}}\n            \n        ###Generated Report:',